set echo on

-- 
-- GUS 3.0 to 3.5 SQL Upgrade Scripts
--
-- **** WARNING *****
--    This script is provided for reference only, and is intended to 
--    be run manually, with human review before and after every command.
--  
--    You should **NOT** run this script automatically.
--   
--    CBIL and the University of Pennsylvania cannot and will not be 
--    responsible for any losses, data or otherwise, resulting from this
--    script. 
--
--    Please see the UPRGADE documentation for full details and instructions. 

-- REVIEW TABLESPACES
-- REVIEW VER CHANGES
-- TABLEINFO CHANGES
-- INSERT INTO DATABASEINFO

exit;

--
-- PRECISION CHANGES
-- 

ALTER TABLE DOTS.AASEQUENCEIMP MODIFY DESCRIPTION VARCHAR2(2000);
ALTER TABLE DOTSVER.AASEQUENCEIMPVER MODIFY DESCRIPTION VARCHAR2(2000);

ALTER TABLE SRES.REFERENCE MODIFY JOURNAL_OR_BOOK_NAME VARCHAR2(1000);
ALTER TABLE SRESVER.REFERENCEVER MODIFY JOURNAL_OR_BOOK_NAME VARCHAR2(1000);

ALTER TABLE SRES.REFERENCE MODIFY AUTHOR VARCHAR2(1000;)
ALTER TABLE SRESVER.REFERENCEVER MODIFY AUTHOR VARCHAR2(1000);

ALTER TABLE SRES.REFERENCE MODIFY TITLE VARCHAR2(1000);
ALTER TABLE SRESVER.REFERENCEVER MODIFY TITLE VARCHAR2(1000);

ALTER TABLE DOTS.LIBRARY MODIFY VECTOR VARCHAR2(156);
ALTER TABLE DOTSVER.LIBRARYVER MODIFY VECTOR VARCHAR2(156);

ALTER TABLE DOTS.LIBRARY MODIFY TISSUE_TYPE VARCHAR2(156);
ALTER TABLE DOTSVER.LIBRARYVER MODIFY TISSUE_TYPE VARCHAR2(156);

ALTER TABLE DOTS.LIBRARY MODIFY STRAIN VARCHAR2(156);
ALTER TABLE DOTSVER.LIBRARYVER MODIFY STRAIN VARCHAR2(156);

ALTER TABLE DOTS.LIBRARY MODIFY CULTIVAR VARCHAR2(156);
ALTER TABLE DOTSVER.LIBRARYVER MODIFY CULTIVAR VARCHAR2(156);

ALTER TABLE DOTS.LIBRARY MODIFY CELL_TYPE VARCHAR2(156);
ALTER TABLE DOTSVER.LIBRARYVER MODIFY CELL_TYPE VARCHAR2(156);

ALTER TABLE RAD3.COMPOSITEELEMENTIMP MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);
ALTER TABLE RAD3VER.COMPOSITEELEMENTIMPVER MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);

ALTER TABLE RAD3.ARRAY MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);
ALTER TABLE RAD3VER.ARRAYVER MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);

ALTER TABLE RAD3.STUDY MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);
ALTER TABLE RAD3VER.STUDYVER MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);

ALTER TABLE RAD3.PROTOCOL MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);
ALTER TABLE RAD3VER.PROTOCOLVER MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);

ALTER TABLE RAD3.ACQUISITIONPARAM MODIFY VALUE VARCHAR2(100);
ALTER TABLE RAD3VER.ACQUISITIONPARAMVER MODIFY VALUE VARCHAR2(100);

ALTER TABLE RAD3.QUANTIFICATIONPARAM MODIFY VALUE VARCHAR2(100);
ALTER TABLE RAD3VER.QUANTIFICATIONPARAMVER MODIFY VALUE VARCHAR2(100);

ALTER TABLE RAD3.ANALYSISPARAM MODIFY VALUE VARCHAR2(100);
ALTER TABLE RAD3VER.ANALYSISPARAMVER MODIFY VALUE VARCHAR2(100);

ALTER TABLE RAD3.ANALYSISQCPARAM MODIFY VALUE VARCHAR2(100);
ALTER TABLE RAD3VER.ANALYSISQCPARAMVER MODIFY VALUE VARCHAR2(100);

--
-- COLUMN RENAMING CHANGES
--

-- SRes.BibliographicReference is loosing pubmed_id and medline_id in favor
-- of source_id and external_database_release_id.  A data migration script
-- is provided below. 

ALTER TABLE SRES.BIBLIOGRAPHICREFERENCE RENAME COLUMN PUBMED_ID TO SOURCE_ID;
ALTER TABLE SRESVER.BIBLIOGRAPHICREFERENCEVER 
      RENAME COLUMN PUBMED_ID TO SOURCE_ID;

ALTER TABLE SRES.BIBLIOGRAPHICREFERENCE RENAME COLUMN MEDLINE_ID TO 
      EXTERNAL_DATABASE_RELEASE_ID;
ALTER TABLE SRESVER.BIBLIOGRAPHICREFERENCEVER RENAME COLUMN MEDLINE_ID TO 
      EXTERNAL_DATABASE_RELEASE_ID;

--- Data migration script ** VERIFY that this is logical for your DB!
--- Here at CBIL, we're just purging the sole medline_id we had

UPDATE SRES.BIBLIOGRAPHICREFERENCE SET EXTERNAL_DATABASE_RELEASE_ID=NULL;

-- REVIEW (NEW CBILBLD TABLE)
ALTER TABLE TESS.REGIONOFINTEREST RENAME COLUMN END TO END_POSITION;
ALTER TABLE TESS.REGIONOFINTEREST RENAME COLUMN BEGIN TO BEGIN_POSITION;

ALTER TABLE TESS.PREDICTEDBINDINGSITE RENAME COLUMN END TO END_POSITION;
ALTER TABLE TESS.PREDICTEDBINDINGSITE RENAME COLUMN BEGIN TO BEGIN_POSITION;

ALTER TABLE TESS.ISLANDOFINTEREST RENAME COLUMN END TO END_POSITION;
ALTER TABLE TESS.ISLANDOFINTEREST RENAME COLUMN BEGIN TO BEGIN_POSITION;

--
-- COLUMN ATTRIBUTE CHANGES

ALTER TABLE RAD3.ANALYSIS MODIFY ANALYSIS_DATE DATE NULL;
ALTER TABLE RAD3VER.ANALYSISVER MODIFY ANALYSIS_DATE DATE NULL;

ALTER TABLE DOTS.ALLELEPHENOTYPECLASS MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.ALLELEINSTANCE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.ACTIVITYIMP MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.AASEQUENCEENZYMECLASS MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.COMPLEMENTATION MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.COMPLEXANATOMY MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.GENEINSTANCE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.PROTEIN MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE SRES.EXTERNALDATABASEENTRY MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.GOASSOCIATIONINSTANCE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.PARAMETERGROUP MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.AAMOTIFGOTERMRULESET MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.GOASSOCINSTEVIDCODE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.RNAINSTANCE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.GOASSOCIATION MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.RNAICONSTRUCT MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.GENE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.AAMOTIFGOTERMRULE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.RNA MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.MOIETYIMP MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.MODELRESULT MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.PROTEINSYNONYM MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.GENESYNONYM MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.MODELIMP MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.PREDICTIONRESULT MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.ALLELECOMPLEMENTATION MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.COMMENTS MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.PROTEININSTANCE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.MOIETYMEMBER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.ANALYSIS MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.COMPLEX MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.INTERACTION MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.RNAIPHENOTYPE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.ALLELEPHENOTYPE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;

ALTER TABLE DOTSVER.ALLELEPHENOTYPECLASSVER MODIFY
       REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.ALLELEINSTANCEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.ACTIVITYIMPVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.AASEQUENCEENZYMECLASSVER MODIFY
       REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.COMPLEMENTATIONVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.COMPLEXANATOMYVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.GENEINSTANCEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.PROTEINVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;

ALTER TABLE SRESVER.EXTERNALDATABASEENTRYVER MODIFY 
      REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.GOASSOCIATIONINSTANCEVER MODIFY 
      REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.PARAMETERGROUPVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.AAMOTIFGOTERMRULESETVER MODIFY 
      REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.GOASSOCINSTEVIDCODEVER MODIFY 
      REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.RNAINSTANCEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.GOASSOCIATIONVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.RNAICONSTRUCTVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;

ALTER TABLE DOTSVER.GENEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.AAMOTIFGOTERMRULEVER MODIFY 
      REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.RNAVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.MOIETYIMPVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.MODELRESULTVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.PROTEINSYNONYMVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.GENESYNONYMVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
--ALTER TABLE TESSVER.MODELIMPVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.PREDICTIONRESULTVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;

ALTER TABLE DOTSVER.ALLELECOMPLEMENTATIONVER MODIFY 
      REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.COMMENTSVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.PROTEININSTANCEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.MOIETYMEMBERVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.ANALYSISVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.COMPLEXVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.INTERACTIONVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.RNAIPHENOTYPEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.ALLELEPHENOTYPEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;

--
-- TABLE CHANGES
-- 

--- this is terrible

-- You must do this next change while logged in as the RAD3 user
rename array to radarray;
-- You must do this next change while logged in as the RAD3VER user
rename arrayver to radarrayver;

update core.tableinfo set name='RadArray' where lower(name)='array' 
       and database_id=(
       select database_id from core.databaseinfo where lower(name)='rad3');
update core.tableinfo set name='RadArrayVer' where lower(name)='arrayver' 
       and database_id=(
       select database_id from core.databaseinfo where lower(name)='rad3ver');



--
-- NEW TABLES
--

-- A new table, Core.DatabaseVersion is being created which will
-- hold the GUS version for use with plugins.  The version column
-- is being removed from Core.DatabaseInfo (which is really schema 
-- info)

CREATE SEQUENCE CORE.DATABASEVERSION_SQ START WITH 1;

CREATE TABLE Core.DatabaseVersion (
       DATABASE_VERSION_ID	NUMBER(5)	NOT NULL,
       VERSION			FLOAT		NOT NULL,
       MODIFICATION_DATE	DATE		NOT NULL,
       USER_READ		NUMBER(1)       NOT NULL,
       USER_WRITE		NUMBER(1)	NOT NULL,
       GROUP_READ		NUMBER(1)	NOT NULL,
       GROUP_WRITE		NUMBER(1)	NOT NULL,
       OTHER_READ		NUMBER(1)	NOT NULL,
       OTHER_WRITE		NUMBER(1)	NOT NULL,
       ROW_USER_ID		NUMBER(12)	NOT NULL,
       ROW_GROUP_ID		NUMBER(12)	NOT NULL, 
       ROW_PROJECT_ID		NUMBER(12)	NOT NULL,
       ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL
);

CREATE TABLE CoreVer.DatabaseVersionVer (
       DATABASE_VERSION_ID	NUMBER(5)	NOT NULL,
       VERSION			FLOAT		NOT NULL,
       MODIFICATION_DATE	DATE		NOT NULL,
       USER_READ		NUMBER(1)       NOT NULL,
       USER_WRITE		NUMBER(1)	NOT NULL,
       GROUP_READ		NUMBER(1)	NOT NULL,
       GROUP_WRITE		NUMBER(1)	NOT NULL,
       OTHER_READ		NUMBER(1)	NOT NULL,
       OTHER_WRITE		NUMBER(1)	NOT NULL,
       ROW_USER_ID		NUMBER(12)	NOT NULL,
       ROW_GROUP_ID		NUMBER(12)	NOT NULL, 
       ROW_PROJECT_ID		NUMBER(12)	NOT NULL,
       ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL,
       VERSION_ALG_INVOCATION_ID NUMBER(12),
       VERSION_DATE		DATE,
       VERSION_TRANSACTION_ID	NUMBER(12)
);

ALTER TABLE Core.DatabaseVersion ADD CONSTRAINT DatabaseVersion_PK
      PRIMARY KEY (DATABASE_VERSION_ID);

ALTER TABLE CoreVer.DatabaseVersionVer ADD CONSTRAINT DatabaseVersion_PK
      PRIMARY KEY (DATABASE_VERSION_ID, MODIFICATION_DATE);

ALTER TABLE CORE.DATABASEINFO DROP COLUMN VERSION;

ALTER TABLE COREVER.DATABASEINFOVER DROP COLUMN VERSION;

--ALTER TABLE SRES.EXTERNALDATABASE DROP COLUMN LOWERCASE_NAME;
--ALTER TABLE SRESVER.EXTERNALDATABASEVER DROP COLUMN LOWERCASE_NAME;

-- A new table, Core.AnalysisAlgorithm is being created to provide any
-- information about a particular analysis to any row in the database.

--- REVIEW
-- As part of this change, algorithm_id will be removed from Dots.Similarity,
-- DoTS.SeqGroupExpirementImp (and views), and DoTS.OpticalMapAlignment. A
-- data migration script has been provided to move these rows.

create sequence core.analysisalgorithm_sq start with 1;

create table core.analysisalgorithm (
        analysis_algorithm_id   number(10) not null,
        table_id                number(5) not null,
        row_id                  number(12) not null,
        algorithm_invocation_id number(12) not null,
        modification_date       date not null,
        user_read               number(1) not null,
        user_write              number(1) not null,
        group_read              number(1) not null,
        group_write             number(1) not null,
        other_read              number(1) not null,
        other_write             number(1) not null,
        row_user_id             number(12) not null,
        row_group_id            number(3) not null,
        row_project_id          number(4) not null,
        row_alg_invocation_id   number(12) not null
);

create table corever.analysisalgorithmver (
        analysis_algorithm_id   number(10) not null,
        table_id                number(5) not null,
        row_id                  number(12) not null,
        algorithm_invocation_id number(12) not null,
        modification_date       date not null,
        user_read               number(1) not null,
        user_write              number(1) not null,
        group_read              number(1) not null,
        group_write             number(1) not null,
        other_read              number(1) not null,
        other_write             number(1) not null,
        row_user_id             number(12) not null,
        row_group_id            number(3) not null,
        row_project_id          number(4) not null,
        row_alg_invocation_id   number(12) not null,
       VERSION_ALG_INVOCATION_ID NUMBER(12),
       VERSION_DATE		DATE,
       VERSION_TRANSACTION_ID	NUMBER(12)
);

ALTER TABLE Core.AnalysisAlgorithm Add Constraint AnalysisAlgorithm_PK
      PRIMARY KEY (Analysis_Algorithm_ID);

ALTER TABLE CoreVer.AnalysisAlgorithmVer Add Constraint AnalysisAlgorithm_PK
      PRIMARY KEY (Analysis_Algorithm_ID, MODIFICATION_DATE);

Alter Table Core.AnalysisAlgorithm Add Constraint AnalysisAlgorithm_FK01
      FOREIGN KEY (TABLE_ID) REFERENCES Core.TableInfo (TABLE_ID);

Alter Table Core.AnalysisAlgorithm Add Constraint AnalysisAlgorithm_FK02
      FOREIGN KEY (Algorithm_Invocation_ID) REFERENCES Core.AlgorithmInvocation
      (ALGORITHM_INVOCATION_ID);

Alter Table DoTS.Similarity Drop Column ALGORITHM_ID;
Alter Table DotsVer.SimilarityVer Drop Column ALGORITHM_ID;

Alter Table DoTS.OpticalMapAlignment Drop Column ALGORITHM_ID;
Alter Table DotsVer.OpticalMapAlignmentVer Drop Column ALGORITHM_ID;

Alter Table DoTS.SeqGroupExperimentImp Drop Column ALGORITHM_ID;
Alter Table DoTSVer.SeqGroupExperimentImpVer Drop Column Algorithm_ID;

--
-- DEPRECATED TABLES
-- 

-- The core.machine table has been deprecated.  There is no replacement or 
-- data migration script provided.

alter table CORE.ALGORITHMINVOCATION drop constraint ALGORITHMINVOCATION_FK04;

alter table core.algorithminvocation drop column machine_id;
alter table corever.algorithminvocationver drop column machine_id;

DROP TABLE CORE.MACHINE;
DROP TABLE COREVER.MACHINEVER;

delete from core.databasedocumentation where table_id=
(select t.table_id from core.tableinfo t, core.databaseinfo d 
	where lower(t.name)='machine' and lower(d.name)='core');
delete from core.databasedocumentation where table_id=
(select t.table_id from core.tableinfo t, core.databaseinfo d 
	where lower(t.name)='machinever' and lower(d.name)='corever');

delete from core.tableinfo where lower(name)='machine' and database_id=(
       select database_id from core.databaseinfo where lower(name)='core');
delete from core.tableinfo where lower(name)='machinever' and database_id=(
       select database_id from core.databaseinfo where lower(name)='corever');

-- DoTS.GeneAlias has been merged with DoTS.GeneSynonym.  A data migration 
-- script is provided below. ** VERIFY that this is logical for your DB!

-- Make sure no rows soft link to GENE.ALIAS

delete from core.databasedocumentation where table_id=
(select t.table_id from core.tableinfo t, core.databaseinfo d 
	where lower(t.name)='genealias' and lower(d.name)='dots');
delete from core.databasedocumentation where table_id=
(select t.table_id from core.tableinfo t, core.databaseinfo d 
	where lower(t.name)='genealiasver' and lower(d.name)='dotsver');

delete from core.tableinfo where lower(name)='genealias' and database_id=(
       select database_id from core.databaseinfo where lower(name)='dots');
delete from core.tableinfo where lower(name)='genealiasver' and database_id=(
       select database_id from core.databaseinfo where lower(name)='dotsver');

-- Move rows from GeneAlias to GeneSynonym

INSERT INTO DOTS.GENESYNONYM SELECT
       DOTS.GENESYNONYM_SQ.nextval,
       GENE_ID,
       GENE_ALIAS_NAME,
       REVIEW_STATUS_ID,
       NULL,
       MODIFICATION_DATE,
       USER_READ,
       USER_WRITE,
       GROUP_READ,
       GROUP_WRITE,
       OTHER_READ,
       OTHER_WRITE,
       ROW_USER_ID,
       ROW_GROUP_ID,
       ROW_PROJECT_ID,
       ROW_ALG_INVOCATION_ID
    FROM DOTS.GENEALIAS;

INSERT INTO DOTSVER.GENESYNONYMVER SELECT
       GENE_ALIAS_ID,
       GENE_ID,
       GENE_ALIAS_NAME,
       REVIEW_STATUS_ID,
       NULL,
       MODIFICATION_DATE,
       USER_READ,
       USER_WRITE,
       GROUP_READ,
       GROUP_WRITE,
       OTHER_READ,
       OTHER_WRITE,
       ROW_USER_ID,
       ROW_GROUP_ID,
       ROW_PROJECT_ID,
       ROW_ALG_INVOCATION_ID,
       VERSION_ALG_INVOCATION_ID,
       VERSION_DATE,
       VERSION_TRANSACTION_ID
    FROM DOTSVER.GENEALIASVER;

DROP TABLE DOTS.GENEALIAS;
DROP TABLE DOTSVER.GENEALIASVER;

-- RAD3.Process tables have been deprecated. 
-- No data migration scripts are provided.

DROP TABLE RAD3.PROCESSIOELEMENT;
DROP TABLE RAD3.PROCESSIO;
DROP TABLE RAD3.PROCESSINVOCATIONPARAM;
DROP TABLE RAD3.PROCESSINVQUANTIFICATION;
DROP TABLE RAD3.PROCESSINVOCATION;
DROP TABLE RAD3.PROCESSIMPLEMENTATION;
DROP TABLE RAD3.PROCESSIMPLEMENTATIONPARAM;
DROP TABLE RAD3.PROCESSRESULT;

DROP TABLE RAD3VER.PROCESSIOELEMENTVER;
DROP TABLE RAD3VER.PROCESSIOVER;
DROP TABLE RAD3VER.PROCESSINVOCATIONPARAMVER;
DROP TABLE RAD3VER.PROCESSINVQUANTIFICATIONVER;
DROP TABLE RAD3VER.PROCESSINVOCATIONVER;
DROP TABLE RAD3VER.PROCESSIMPLEMENTATIONVER;
DROP TABLE RAD3VER.PROCESSIMPLEMENTATIONPARAMVER;
DROP TABLE RAD3VER.PROCESSRESULTVER;

-- The RAD3.GNFAffymetixResult view has been deprecated.

DROP VIEW RAD3.GNFAffymetrixResult;
-- Delete rows?