set echo on

-- 
-- GUS 3.0 to 3.5 SQL Upgrade Scripts
--
-- **** WARNING *****
--    This script is provided for reference only, and is intended to 
--    be run manually, with human review before and after every command.
--  
--    You should **NOT** run this script automatically.
--   
--    CBIL and the University of Pennsylvania cannot and will not be 
--    responsible for any losses, data or otherwise, resulting from this
--    script. 
--
--    Please see the UPRGADE documentation for full details and instructions. 

-- REVIEW TABLESPACES
-- REVIEW VER CHANGES
-- TABLEINFO CHANGES
-- INSERT INTO DATABASEINFO

exit;

--
-- PRECISION CHANGES
-- 

ALTER TABLE DOTS.AASEQUENCEIMP MODIFY DESCRIPTION VARCHAR2(2000);
ALTER TABLE DOTSVER.AASEQUENCEIMPVER MODIFY DESCRIPTION VARCHAR2(2000);

ALTER TABLE SRES.REFERENCE MODIFY JOURNAL_OR_BOOK_NAME VARCHAR2(1000);
ALTER TABLE SRESVER.REFERENCEVER MODIFY JOURNAL_OR_BOOK_NAME VARCHAR2(1000);

ALTER TABLE SRES.REFERENCE MODIFY AUTHOR VARCHAR2(1000;)
ALTER TABLE SRESVER.REFERENCEVER MODIFY AUTHOR VARCHAR2(1000);

ALTER TABLE SRES.REFERENCE MODIFY TITLE VARCHAR2(1000);
ALTER TABLE SRESVER.REFERENCEVER MODIFY TITLE VARCHAR2(1000);

ALTER TABLE DOTS.LIBRARY MODIFY VECTOR VARCHAR2(156);
ALTER TABLE DOTSVER.LIBRARYVER MODIFY VECTOR VARCHAR2(156);

ALTER TABLE DOTS.LIBRARY MODIFY TISSUE_TYPE VARCHAR2(156);
ALTER TABLE DOTSVER.LIBRARYVER MODIFY TISSUE_TYPE VARCHAR2(156);

ALTER TABLE DOTS.LIBRARY MODIFY STRAIN VARCHAR2(156);
ALTER TABLE DOTSVER.LIBRARYVER MODIFY STRAIN VARCHAR2(156);

ALTER TABLE DOTS.LIBRARY MODIFY CULTIVAR VARCHAR2(156);
ALTER TABLE DOTSVER.LIBRARYVER MODIFY CULTIVAR VARCHAR2(156);

ALTER TABLE DOTS.LIBRARY MODIFY CELL_TYPE VARCHAR2(156);
ALTER TABLE DOTSVER.LIBRARYVER MODIFY CELL_TYPE VARCHAR2(156);

ALTER TABLE RAD3.COMPOSITEELEMENTIMP MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);
ALTER TABLE RAD3VER.COMPOSITEELEMENTIMPVER MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);

ALTER TABLE RAD3.ARRAY MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);
ALTER TABLE RAD3VER.ARRAYVER MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);

ALTER TABLE RAD3.STUDY MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);
ALTER TABLE RAD3VER.STUDYVER MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);

ALTER TABLE RAD3.PROTOCOL MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);
ALTER TABLE RAD3VER.PROTOCOLVER MODIFY 
      EXTERNAL_DATABASE_RELEASE_ID NUMBER(12);

ALTER TABLE RAD3.ACQUISITIONPARAM MODIFY VALUE VARCHAR2(100);
ALTER TABLE RAD3VER.ACQUISITIONPARAMVER MODIFY VALUE VARCHAR2(100);

ALTER TABLE RAD3.QUANTIFICATIONPARAM MODIFY VALUE VARCHAR2(100);
ALTER TABLE RAD3VER.QUANTIFICATIONPARAMVER MODIFY VALUE VARCHAR2(100);

ALTER TABLE RAD3.ANALYSISPARAM MODIFY VALUE VARCHAR2(100);
ALTER TABLE RAD3VER.ANALYSISPARAMVER MODIFY VALUE VARCHAR2(100);

ALTER TABLE RAD3.ANALYSISQCPARAM MODIFY VALUE VARCHAR2(100);
ALTER TABLE RAD3VER.ANALYSISQCPARAMVER MODIFY VALUE VARCHAR2(100);

--
-- COLUMN RENAMING CHANGES
--

-- SRes.BibliographicReference is loosing pubmed_id and medline_id in favor
-- of source_id and external_database_release_id.  A data migration script
-- is provided below. 

ALTER TABLE SRES.BIBLIOGRAPHICREFERENCE RENAME COLUMN PUBMED_ID TO SOURCE_ID;
ALTER TABLE SRESVER.BIBLIOGRAPHICREFERENCEVER 
      RENAME COLUMN PUBMED_ID TO SOURCE_ID;

ALTER TABLE SRES.BIBLIOGRAPHICREFERENCE RENAME COLUMN MEDLINE_ID TO 
      EXTERNAL_DATABASE_RELEASE_ID;
ALTER TABLE SRESVER.BIBLIOGRAPHICREFERENCEVER RENAME COLUMN MEDLINE_ID TO 
      EXTERNAL_DATABASE_RELEASE_ID;

--- Data migration script ** VERIFY that this is logical for your DB!
--- Here at CBIL, we're just purging the sole medline_id we had

UPDATE SRES.BIBLIOGRAPHICREFERENCE SET EXTERNAL_DATABASE_RELEASE_ID=NULL;

-- Add PUBMED entry to external DB

-- REVIEW (NEW CBILBLD TABLE)
ALTER TABLE TESS.REGIONOFINTEREST RENAME COLUMN END TO END_POSITION;
ALTER TABLE TESS.REGIONOFINTEREST RENAME COLUMN BEGIN TO BEGIN_POSITION;

ALTER TABLE TESS.PREDICTEDBINDINGSITE RENAME COLUMN END TO END_POSITION;
ALTER TABLE TESS.PREDICTEDBINDINGSITE RENAME COLUMN BEGIN TO BEGIN_POSITION;

ALTER TABLE TESS.ISLANDOFINTEREST RENAME COLUMN END TO END_POSITION;
ALTER TABLE TESS.ISLANDOFINTEREST RENAME COLUMN BEGIN TO BEGIN_POSITION;

ALTER TABLE DOTS.PLASMOMAP RENAME COLUMN CROSS TO OUTCROSS;
ALTER TABLE DOTSVER.PLASMOMAPVER RENAME COLUMN CROSS TO OUTCROSS;

--
-- COLUMN ATTRIBUTE CHANGES

ALTER TABLE RAD3.ANALYSIS MODIFY ANALYSIS_DATE DATE NULL;
ALTER TABLE RAD3VER.ANALYSISVER MODIFY ANALYSIS_DATE DATE NULL;

ALTER TABLE DOTS.ALLELEPHENOTYPECLASS MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.ALLELEINSTANCE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.ACTIVITYIMP MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.AASEQUENCEENZYMECLASS MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.COMPLEMENTATION MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.COMPLEXANATOMY MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.GENEINSTANCE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.PROTEIN MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE SRES.EXTERNALDATABASEENTRY MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.GOASSOCIATIONINSTANCE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.PARAMETERGROUP MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.AAMOTIFGOTERMRULESET MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.GOASSOCINSTEVIDCODE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.RNAINSTANCE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.GOASSOCIATION MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.RNAICONSTRUCT MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.GENE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.AAMOTIFGOTERMRULE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.RNA MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.MOIETYIMP MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.MODELRESULT MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.PROTEINSYNONYM MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.GENESYNONYM MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.MODELIMP MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.PREDICTIONRESULT MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.ALLELECOMPLEMENTATION MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.COMMENTS MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.PROTEININSTANCE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.MOIETYMEMBER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESS.ANALYSIS MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.COMPLEX MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.INTERACTION MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.RNAIPHENOTYPE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTS.ALLELEPHENOTYPE MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;

ALTER TABLE DOTSVER.ALLELEPHENOTYPECLASSVER MODIFY
       REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.ALLELEINSTANCEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.ACTIVITYIMPVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.AASEQUENCEENZYMECLASSVER MODIFY
       REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.COMPLEMENTATIONVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.COMPLEXANATOMYVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.GENEINSTANCEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.PROTEINVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;

ALTER TABLE SRESVER.EXTERNALDATABASEENTRYVER MODIFY 
      REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.GOASSOCIATIONINSTANCEVER MODIFY 
      REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.PARAMETERGROUPVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.AAMOTIFGOTERMRULESETVER MODIFY 
      REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.GOASSOCINSTEVIDCODEVER MODIFY 
      REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.RNAINSTANCEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.GOASSOCIATIONVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.RNAICONSTRUCTVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;

ALTER TABLE DOTSVER.GENEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.AAMOTIFGOTERMRULEVER MODIFY 
      REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.RNAVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.MOIETYIMPVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.MODELRESULTVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.PROTEINSYNONYMVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.GENESYNONYMVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
--ALTER TABLE TESSVER.MODELIMPVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.PREDICTIONRESULTVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;

ALTER TABLE DOTSVER.ALLELECOMPLEMENTATIONVER MODIFY 
      REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.COMMENTSVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.PROTEININSTANCEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.MOIETYMEMBERVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE TESSVER.ANALYSISVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.COMPLEXVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.INTERACTIONVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.RNAIPHENOTYPEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;
ALTER TABLE DOTSVER.ALLELEPHENOTYPEVER MODIFY REVIEW_STATUS_ID NUMBER(12) NULL;

ALTER TABLE DOTS.NASEQUENCEIMP MODIFY SEQUENCE_TYPE_ID NUMBER(4) NULL;
ALTER TABLE DOTSVER.NASEQUENCEIMPVER MODIFY SEQUENCE_TYPE_ID NUMBER(4) NULL;

ALTER TABLE DOTS.GENEINSTANCE MODIFY GENE_INSTANCE_CATEGORY_ID NUMBER(3) NULL;
ALTER TABLE DOTSVER.GENEINSTANCEVER MODIFY GENE_INSTANCE_CATEGORY_ID
      NUMBER(3) NULL;

ALTER TABLE DOTS.RNAINSTANCE MODIFY RNA_INSTANCE_CATEGORY_ID NUMBER(3) NULL;
ALTER TABLE DOTSVER.RNAINSTANCEVER MODIFY RNA_INSTANCE_CATEGORY_ID
      NUMBER(3) NULL;

ALTER TABLE DOTS.PROTEININSTANCE MODIFY PROTEIN_INSTANCE_CATEGORY_ID 
      NUMBER(3) NULL;
ALTER TABLE DOTSVER.PROTEININSTANCEVER MODIFY PROTEIN_INSTANCE_CATEGORY_ID
      NUMBER(3) NULL;
--
-- TABLE CHANGES
-- 

-- You must do this next change while logged in as the RAD3 user
rename array to reporterarray;
-- You must do this next change while logged in as the RAD3VER user
rename arrayver to reporterarrayver;

ALTER TABLE RAD3.REPORTERARRAY RENAME COLUMN ARRAY_ID TO REPORTER_ARRAY_ID;
ALTER TABLE RAD3VER.REPORTERARRAYVER RENAME 
      COLUMN ARRAY_ID TO REPORTER_ARRAY_ID;

update core.tableinfo set name='ReporterArray' where lower(name)='array' 
       and database_id=(
       select database_id from core.databaseinfo where lower(name)='rad3');
update core.tableinfo set name='ReporterArrayVer' where lower(name)='arrayver' 
       and database_id=(
       select database_id from core.databaseinfo where lower(name)='rad3ver');

-- You must do these next changes while logged in as the SRes user
rename MGEDOntologyTerm to OntologyTerm;
rename MGEDOntologyRelationship to OntologyRelationship;
rename MGEDOntologyTerm_SQ to OntologyTerm_SQ;
rename MGEDOntologyRelationship_SQ to OntologyRelationsip;
-- You must do these next changes while logged in as the SResVer user
rename MGEDOntologyTermVer to OntologyTermVer;
rename MGEDOntologyRelationshipVer to OntologyRelationshipVer;

ALTER TABLE SRES.ONTOLOGYTERM RENAME 
      COLUMN MGED_ONTOLOGY_TERM_ID TO ONTOLOGY_TERM_ID;
ALTER TABLE SRESVER.ONTOLOGYTERMVER RENAME 
      COLUMN MGED_ONTOLOGY_TERM_ID TO ONTOLOGY_TERM_ID;

ALTER TABLE SRES.ONTOLOGYRELATIONSHIP RENAME 
      COLUMN MGED_ONTOLOGY_RELATIONSHIP_ID TO ONTOLOGY_RELATIONSHIP_ID;
ALTER TABLE SRESVER.ONTOLOGYRELATIONSHIPVER RENAME 
      COLUMN MGED_ONTOLOGY_RELATIONSHIP_ID TO ONTOLOGY_RELATIONSHIP_ID;

update core.tableinfo set name='OntologyTerm', 
       primary_key_column='ONTOLOGY_TERM_ID' where 
       lower(name)='mgedontologyterm' 
       and database_id=(
       select database_id from core.databaseinfo where lower(name)='sres');
update core.tableinfo set name='OntologyTermVer' where 
       lower(name)='mgedontologytermver' 
       and database_id=(
       select database_id from core.databaseinfo where lower(name)='sresver');

update core.tableinfo set name='OntologyRelationship',
       primary_key_column='ONTOLOGY_RELATIONSHIP_ID' where 
       lower(name)='mgedontologyrelationship' 
       and database_id=(
       select database_id from core.databaseinfo where lower(name)='sres');
update core.tableinfo set name='OntologyRelationshipVer' where 
       lower(name)='mgedontologyrelationshipver' 
       and database_id=(
       select database_id from core.databaseinfo where lower(name)='sresver');

--
-- COLUMN ADDITIONS
-- 

-- Because GUS 3.5 requires requires the housekeeping columns to be
-- in a specific order at the "end" of the table, adding a column 
-- involves moving the old table out of the way, creating a new
-- table from the old, adding constraints and indexes to the new
-- table, and then dropping the old.

-- This change must be made as the Core user
rename projectinfo to projectinfo_old;
-- This change must be made as the CoreVer user
rename projectinfover to projectinfover_old;
-- These changes must be made as the dots user
rename nasequenceimp to nasequenceimp_old;
rename aasequenceimp to aasequenceimp_old;
rename gene to gene_old;
rename rna to rna_old;
rename protein to protein_old;
-- These changes must be made as the dotsver user-
rename nasequenceimpver to nasequenceimpver_old;
rename aasequenceimpver to aasequenceimpver_old;
rename genever to genever_old;
rename rnaver to rnaver_old;
rename proteinver to proteinver_old;
-- These changes must be made as the rad3 user
rename reporterarray to reporterarray_old;
rename elementimp to elementimp_old;
-- These changes must be made as the rad3ver user
rename reporterarrayver to reporterarrayver_old;
rename elementimpver to elementimpver_old;

-- Now, recreate tables

-- Core.ProjectInfo

CREATE TABLE Core.PROJECTINFO (
    PROJECT_ID	NUMBER(4)	NOT NULL,
    NAME		VARCHAR2(40)	NOT NULL,
    DESCRIPTION	VARCHAR2(255)	NULL,
    RELEASE     VARCHAR2(20)    NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(12)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(12)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL);

INSERT INTO Core.ProjectInfo SELECT 
       PROJECT_ID, NAME, DESCRIPTION, null, 
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID
       FROM Core.ProjectInfo_old;

alter table DOTS.PROJECTLINK drop constraint PROJECTLINK_FK05;
alter table CORE.USERPROJECT drop constraint USERPROJECT_FK06;
alter table RAD3.PROJECTLINK drop constraint FK_PROJLINK_PROJINFO;

DROP TABLE Core.ProjectInfo_Old;

grant references on core.projectinfo to dots;
grant references on core.projectinfo to rad3;

alter table core.projectinfo add constraint
      PK_PROJECTINFO primary key (PROJECT_ID);

alter table DOTS.PROJECTLINK add constraint 
      PROJECTLINK_FK05 foreign key (PROJECT_ID) 
      references CORE.PROJECTINFO (PROJECT_ID);

alter table CORE.USERPROJECT add constraint 
      USERPROJECT_FK06 foreign key (PROJECT_ID) 
      references CORE.PROJECTINFO (PROJECT_ID);

alter table RAD3.PROJECTLINK add constraint 
      FK_PROJLINK_PROJINFO foreign key (PROJECT_ID) 
      references CORE.PROJECTINFO (PROJECT_ID);

CREATE TABLE CoreVer.PROJECTINFOVer (
    PROJECT_ID	NUMBER(4)	NOT NULL,
    NAME		VARCHAR2(40)	NOT NULL,
    DESCRIPTION	VARCHAR2(255)	NULL,
    RELEASE     VARCHAR2(20)    NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(12)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(12)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL,
    VERSION_ALG_INVOCATION_ID	NUMBER(12)	NULL,
    VERSION_DATE		DATE		NULL,
    VERSION_TRANSACTION_ID	NUMBER(12)	NULL);

INSERT INTO CoreVer.ProjectInfoVer SELECT 
       PROJECT_ID, NAME, DESCRIPTION, null, 
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID,
       VERSION_ALG_INVOCATION_ID, VERSION_DATE,
       VERSION_TRANSACTION_ID
       FROM CoreVer.ProjectInfoVer_old;

DROP TABLE COREVER.PROJECTINFOVER_OLD;

alter table corever.projectinfover add constraint
      PK_PROJECT_INFO primary key (PROJECT_ID, MODIFICATION_DATE);


-- RAD3.ReporterArray

CREATE TABLE RAD3.REPORTERARRAY (
    REPORTER_ARRAY_ID	NUMBER(4)	NOT NULL,
    MANUFACTURER_ID	NUMBER(12)	NOT NULL,
    PLATFORM_TYPE_ID	NUMBER(8)	NOT NULL,
    SUBSTRATE_TYPE_ID	NUMBER(8)	NULL,
    PROTOCOL_ID	NUMBER(12)	NULL,
    EXTERNAL_DATABASE_RELEASE_ID	NUMBER(12)	NULL,
    SOURCE_ID	VARCHAR2(100)	NULL,
    NAME	VARCHAR2(100)	NOT NULL,
    VERSION	VARCHAR2(50)	NULL,
    DESCRIPTION	VARCHAR2(2000)	NULL,
    ARRAY_DIMENSIONS	VARCHAR2(50)	NULL,
    ELEMENT_DIMENSIONS	VARCHAR2(50)	NULL,
    NUMBER_OF_ELEMENTS	NUMBER(10)	NULL,
    NUM_ARRAY_COLUMNS	NUMBER(3)	NULL,
    NUM_ARRAY_ROWS	NUMBER(3)	NULL,
    NUM_GRID_COLUMNS	NUMBER(3)	NULL,
    NUM_GRID_ROWS	NUMBER(3)	NULL,
    NUM_SUB_COLUMNS	NUMBER(6)	NULL,
    NUM_SUB_ROWS	NUMBER(6)	NULL,
    SURFACE_TYPE_ID	NUMBER(10) NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(12)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(12)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL);

INSERT INTO RAD3.REPORTERARRAY SELECT
       REPORTER_ARRAY_ID, MANUFACTURER_ID, PLATFORM_TYPE_ID,
       SUBSTRATE_TYPE_ID, PROTOCOL_ID, EXTERNAL_DATABASE_RELEASE_ID,
       SOURCE_ID, NAME, VERSION, DESCRIPTION, ARRAY_DIMENSIONS,
       ELEMENT_DIMENSIONS, NUMBER_OF_ELEMENTS, NUM_ARRAY_COLUMNS,
       NUM_ARRAY_ROWS, NUM_GRID_COLUMNS, NUM_GRID_ROWS, NUM_SUB_COLUMNS,
       NUM_SUB_ROWS, null, 
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID
       FROM RAD3.REPORTERARRAY_OLD;

alter table RAD3.ARRAYANNOTATION drop constraint FK_ARRAYANN_ARRAY;
alter table RAD3.ARRAYGROUPLINK drop constraint FK_ARRAYGROUPLINKARRAY;
alter table RAD3.ASSAY drop constraint FK_ASSAY_ARRAY;
alter table RAD3.COMPOSITEELEMENTIMP drop constraint FK_CE_ARRAY;
alter table RAD3.ELEMENTIMP_OLD drop constraint FK_ELEMENT_ARRAY;

drop table rad3.reporterarray_old;

alter table rad3.reporterarray add constraint
       PK_REPORTER_ARRAY primary key (REPORTER_ARRAY_ID)
alter table RAD3.ARRAYANNOTATION add constraint 
      FK_ARRAYANN_ARRAY foreign key (ARRAY_ID) references 
      RAD3.REPORTERARRAY (REPORTER_ARRAY_ID);
alter table RAD3.ARRAYGROUPLINK add constraint 
      FK_ARRAYGROUPLINKARRAY foreign key (ARRAY_ID) 
      references RAD3.REPORTERARRAY (REPORTER_ARRAY_ID);
alter table RAD3.ASSAY add constraint
       FK_ASSAY_ARRAY foreign key (ARRAY_ID) references 
       RAD3.REPORTERARRAY (REPORTER_ARRAY_ID);
alter table RAD3.COMPOSITEELEMENTIMP 
      add constraint FK_CE_ARRAY foreign key (ARRAY_ID) 
      references RAD3.REPORTERARRAY (REPORTER_ARRAY_ID);

alter table rad3.reporterarray add constraint FK_ARRAY_ONTO01 
      foreign key (PLATFORM_TYPE_ID) 
      references RAD3.ONTOLOGYENTRY (ONTOLOGY_ENTRY_ID);
alter table rad3.reporterarray add constraint 
      FK_ARRAY_ONTO02 foreign key (SUBSTRATE_TYPE_ID) 
      references RAD3.ONTOLOGYENTRY (ONTOLOGY_ENTRY_ID);
alter table rad3.reporterarray add constraint FK_ARRAY_PROTOCOL 
      foreign key (PROTOCOL_ID) references RAD3.PROTOCOL (PROTOCOL_ID);
alter table rad3.reporterarray add constraint FK_ARRAY_CONTACT 
      foreign key (MANUFACTURER_ID) references SRES.CONTACT (CONTACT_ID);
alter table rad3.reporterarray add constraint FK_ARRAY_EXTDB 
      foreign key (EXTERNAL_DATABASE_RELEASE_ID) 
      references SRES.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table rad3.reporterarray add constraint FK_SURFACE_TYPE_ID
      foreign key (SURFACE_TYPE_ID) references RAD3.ONTOLOGYENTRY
      (ONTOLOGY_ENTRY_ID);

CREATE TABLE RAD3VER.REPORTERARRAYVER (
    REPORTER_ARRAY_ID	NUMBER(4)	NOT NULL,
    MANUFACTURER_ID	NUMBER(12)	NOT NULL,
    PLATFORM_TYPE_ID	NUMBER(8)	NOT NULL,
    SUBSTRATE_TYPE_ID	NUMBER(8)	NULL,
    PROTOCOL_ID	NUMBER(12)	NULL,
    EXTERNAL_DATABASE_RELEASE_ID	NUMBER(12)	NULL,
    SOURCE_ID	VARCHAR2(100)	NULL,
    NAME	VARCHAR2(100)	NOT NULL,
    VERSION	VARCHAR2(50)	NULL,
    DESCRIPTION	VARCHAR2(2000)	NULL,
    ARRAY_DIMENSIONS	VARCHAR2(50)	NULL,
    ELEMENT_DIMENSIONS	VARCHAR2(50)	NULL,
    NUMBER_OF_ELEMENTS	NUMBER(10)	NULL,
    NUM_ARRAY_COLUMNS	NUMBER(3)	NULL,
    NUM_ARRAY_ROWS	NUMBER(3)	NULL,
    NUM_GRID_COLUMNS	NUMBER(3)	NULL,
    NUM_GRID_ROWS	NUMBER(3)	NULL,
    NUM_SUB_COLUMNS	NUMBER(6)	NULL,
    NUM_SUB_ROWS	NUMBER(6)	NULL,
    SURFACE_TYPE_ID	NUMBER(10) NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(12)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(12)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL,
    VERSION_ALG_INVOCATION_ID	NUMBER(12)	NULL,
    VERSION_DATE		DATE		NULL,
    VERSION_TRANSACTION_ID	NUMBER(12)	NULL);

INSERT INTO RAD3VER.REPORTERARRAYVER SELECT
       REPORTER_ARRAY_ID, MANUFACTURER_ID, PLATFORM_TYPE_ID,
       SUBSTRATE_TYPE_ID, PROTOCOL_ID, EXTERNAL_DATABASE_RELEASE_ID,
       SOURCE_ID, NAME, VERSION, DESCRIPTION, ARRAY_DIMENSIONS,
       ELEMENT_DIMENSIONS, NUMBER_OF_ELEMENTS, NUM_ARRAY_COLUMNS,
       NUM_ARRAY_ROWS, NUM_GRID_COLUMNS, NUM_GRID_ROWS, NUM_SUB_COLUMNS,
       NUM_SUB_ROWS, null, 
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID, 
       VERSION_ALG_INVOCATION_ID, VERSION_DATE,
       VERSION_TRANSACTION_ID
       FROM RAD3VER.REPORTERARRAYVER_OLD;

DROP TABLE RAD3VER.REPORTERARRAYVER_OLD;

alter table rad3ver.reporterarrayver add constraint
       PK_REPORTER_ARRAY primary key (REPORTER_ARRAY_ID, MODIFICATION_DATE);

-- RAD3.ElementImp

CREATE TABLE RAD3.ELEMENTIMP (
    ELEMENT_ID	NUMBER(10)	NOT NULL,
    COMPOSITE_ELEMENT_ID	NUMBER(10)	NULL,
    REPORTER_ARRAY_ID	NUMBER(4)	NOT NULL,
    ELEMENT_TYPE_ID	NUMBER(8)	NULL,
    EXTERNAL_DATABASE_RELEASE_ID	NUMBER(5)	NULL,
    SOURCE_ID	VARCHAR2(50)	NULL,
    SUBCLASS_VIEW	VARCHAR2(27)	NOT NULL,
    PHYSICAL_BIOSEQUENCE_TYPE_ID	NUMBER(10)	NULL,
    POLYMER_TYPE_ID	NUMBER(10)	NULL,
    TINYINT1	NUMBER(3)	NULL,
    SMALLINT1	NUMBER(5)	NULL,
    CHAR1	VARCHAR2(5)	NULL,
    CHAR2	VARCHAR2(5)	NULL,
    CHAR3	VARCHAR2(5)	NULL,
    CHAR4	VARCHAR2(5)	NULL,
    CHAR5	VARCHAR2(5)	NULL,
    CHAR6	VARCHAR2(5)	NULL,
    CHAR7	VARCHAR2(5)	NULL,
    TINYSTRING1	VARCHAR2(50)	NULL,
    TINYSTRING2	VARCHAR2(50)	NULL,
    SMALLSTRING1	VARCHAR2(100)	NULL,
    SMALLSTRING2	VARCHAR2(100)	NULL,
    STRING1	VARCHAR2(500)	NULL,
    STRING2	VARCHAR2(500)	NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_GROUP_ID	NUMBER(12)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(12)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL);

INSERT INTO RAD3.ELEMENTIMP SELECT
       ELEMENT_ID, COMPOSITE_ELEMENT_ID, ARRAY_ID, ELEMENT_TYPE_ID,
       EXTERNAL_DATABASE_RELEASE_ID, SOURCE_ID, SUBCLASS_VIEW,
       null, null, TINYINT1, SMALLINT1, CHAR1, CHAR2, CHAR3, CHAR4,
       CHAR5, CHAR6, CHAR7, TINYSTRING1, TINYSTRING2, SMALLSTRING1,
       SMALLSTRING2, STRING1, STRING2, 
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID
       FROM RAD3.ELEMENTIMP_OLD;

alter table RAD3.ELEMENTANNOTATION drop constraint FK_ELEANNOT_ELEMENTIMP;
alter table RAD3.ELEMENTRESULTIMP drop constraint FK_ELEMENTRESULT_ELEMENTIMP;

drop table rad3.elementimp_old;

alter table rad3.elementimp add constraint PK_ELEMENT primary key (ELEMENT_ID)
alter table RAD3.ELEMENTANNOTATION 
      add constraint FK_ELEANNOT_ELEMENTIMP 
      foreign key (ELEMENT_ID) references RAD3.ELEMENTIMP (ELEMENT_ID);
alter table RAD3.ELEMENTRESULTIMP add constraint 
      FK_ELEMENTRESULT_ELEMENTIMP foreign key (ELEMENT_ID) 
      references RAD3.ELEMENTIMP (ELEMENT_ID);
alter table rad3.elementimp add constraint FK_ELEMENT_ARRAY 
      foreign key (REPORTER_ARRAY_ID) references 
      RAD3.REPORTERARRAY (REPORTER_ARRAY_ID);
alter table rad3.elementimp add constraint FK_ELEMENT_COMPELEFAM 
      foreign key (COMPOSITE_ELEMENT_ID) references 
      RAD3.COMPOSITEELEMENTIMP (COMPOSITE_ELEMENT_ID);aa
alter table rad3.elementimp add constraint FK_ELEMENT_ONTO 
      foreign key (ELEMENT_TYPE_ID) references 
      RAD3.ONTOLOGYENTRY (ONTOLOGY_ENTRY_ID);
alter table rad3.elementimp add constraint FK_ELIMP_EXTDB 
      foreign key (EXTERNAL_DATABASE_RELEASE_ID) references
       SRES.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table rad3.elementimp add constraint FK_PHY_BIOSEQ
      foreign key (PHYSICAL_BIOSEQUENCE_TYPE_ID) references 
      RAD3.ONTOLOGYENTRY (ONTOLOGY_ENTRY_ID);
alter table rad3.elementimp add constraint FK_POLYMER_TYPE_ID
      foreign key (POLYMER_TYPE_ID) references 
      RAD3.ONTOLOGYENTRY (ONTOLOGY_ENTRY_ID);


create index RAD3.RAD3_SPOT_IND02 on rad3.elementimp (COMPOSITE_ELEMENT_ID);
create index RAD3.SHORTOLIGO_IND02 on rad3.elementimp (ELEMENT_TYPE_ID);
create index RAD3.SHORTOLIGO_IND03 on rad3.elementimp 
	(EXTERNAL_DATABASE_RELEASE_ID);
create index RAD3.SAGETAGMAPPING_IND01 on rad3.elementimp 
	(SOURCE_ID,COMPOSITE_ELEMENT_ID);
create index RAD3.SPOT_IND01 on rad3.elementimp 
	(REPORTER_ARRAY_ID,CHAR1,CHAR2,CHAR3,CHAR4,CHAR5,CHAR6);
create index RAD3.ARRAY_IND01 on rad3.elementimp (REPORTER_ARRAY_ID;)
create index RAD3.SHORTOLIGO_IND01 on rad3.elementimp 
       (REPORTER_ARRAY_ID,TINYSTRING1,TINYSTRING2);
create index RAD3.ELEMENTIMP_IND01 on rad3.elementimp (SUBCLASS_VIEW);

CREATE TABLE RAD3VER.ELEMENTIMPVER (
    ELEMENT_ID	NUMBER(10)	NOT NULL,
    COMPOSITE_ELEMENT_ID	NUMBER(10)	NULL,
    REPORTER_ARRAY_ID	NUMBER(4)	NOT NULL,
    ELEMENT_TYPE_ID	NUMBER(8)	NULL,
    EXTERNAL_DATABASE_RELEASE_ID	NUMBER(5)	NULL,
    SOURCE_ID	VARCHAR2(50)	NULL,
    SUBCLASS_VIEW	VARCHAR2(27)	NOT NULL,
    PHYSICAL_BIOSEQUENCE_TYPE_ID	NUMBER(10)	NULL,
    POLYMER_TYPE_ID	NUMBER(10)	NULL,
    TINYINT1	NUMBER(3)	NULL,
    SMALLINT1	NUMBER(5)	NULL,
    CHAR1	VARCHAR2(5)	NULL,
    CHAR2	VARCHAR2(5)	NULL,
    CHAR3	VARCHAR2(5)	NULL,
    CHAR4	VARCHAR2(5)	NULL,
    CHAR5	VARCHAR2(5)	NULL,
    CHAR6	VARCHAR2(5)	NULL,
    CHAR7	VARCHAR2(5)	NULL,
    TINYSTRING1	VARCHAR2(50)	NULL,
    TINYSTRING2	VARCHAR2(50)	NULL,
    SMALLSTRING1	VARCHAR2(100)	NULL,
    SMALLSTRING2	VARCHAR2(100)	NULL,
    STRING1	VARCHAR2(500)	NULL,
    STRING2	VARCHAR2(500)	NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_GROUP_ID	NUMBER(12)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(12)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL,
    VERSION_ALG_INVOCATION_ID	NUMBER(12)	NULL,
    VERSION_DATE		DATE		NULL,
    VERSION_TRANSACTION_ID	NUMBER(12)	NULL);

INSERT INTO RAD3VER.ELEMENTIMPVER SELECT
       ELEMENT_ID, COMPOSITE_ELEMENT_ID, ARRAY_ID, ELEMENT_TYPE_ID,
       EXTERNAL_DATABASE_RELEASE_ID, SOURCE_ID, SUBCLASS_VIEW,
       null, null, TINYINT1, SMALLINT1, CHAR1, CHAR2, CHAR3, CHAR4,
       CHAR5, CHAR6, CHAR7, TINYSTRING1, TINYSTRING2, SMALLSTRING1,
       SMALLSTRING2, STRING1, STRING2, 
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID,
       VERSION_ALG_INVOCATION_ID, VERSION_DATE,
       VERSION_TRANSACTION_ID
       FROM RAD3VER.ELEMENTIMPVER_OLD;

DROP TABLE RAD3VER.ELEMENTIMPVER_OLD;

alter table rad3ver.elementimpver add constraint
       PK_ELEMENT_ID primary key (ELEMENT_ID, MODIFICATION_DATE);

-- DoTS.AASequenceImp

CREATE TABLE DoTS.AASEQUENCEIMP (
    AA_SEQUENCE_ID		NUMBER(10)	NOT NULL,
    SEQUENCE_VERSION		NUMBER(3)	 NULL,
    SUBCLASS_VIEW	VARCHAR2(30)	NOT NULL,
    MOLECULAR_WEIGHT	NUMBER(12)	NULL,
    SEQUENCE	CLOB	NULL,
    LENGTH	NUMBER(12)	NULL,
    DESCRIPTION	VARCHAR2(1024)	NULL,
    EXTERNAL_DATABASE_RELEASE_ID	NUMBER(10)	NULL,
    SOURCE_ID	VARCHAR2(32)	NULL,
    SOURCE_AA_SEQUENCE_ID	NUMBER(10)	NULL,
    SEQUENCE_TYPE_ID		NUMBER(4)		NULL,
    SEQUENCE_ONTOLOGY_ID	  NUMBER(10)	NULL,
    TAXON_ID			  NUMBER(10)	NULL,
    TINYINT1	NUMBER(3)	NULL,
    STRING1	VARCHAR2(255)	NULL,
    STRING2	VARCHAR2(255)	NULL,
    STRING3	VARCHAR2(255)	NULL,
    STRING4	VARCHAR2(255)	NULL,
    INT1	NUMBER(12)	NULL,
    INT2	NUMBER(12)	NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(3)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(3)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL);

INSERT INTO DOTS.AASEQUENCEIMP SELECT
       AA_SEQUENCE_ID, SEQUENCE_VERSION, SUBCLASS_VIEW,
       MOLECULAR_WEIGHT, SEQUENCE, LENGTH, DESCRIPTION,
       EXTERNAL_DATABASE_RELEASE_ID, SOURCE_ID, 
       SOURCE_AA_SEQUENCE_ID, null, null, null, TINYINT1,
       STRING1, STRING2, STRING3, STRING4, INT1, INT2,
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID
       FROM DOTS.AASEQUENCEIMP_OLD;

alter table DOTS.AACOMMENT drop constraint AACOMMENT_FK04;
alter table DOTS.AAENTRY drop constraint AAENTRY_FK04;
alter table DOTS.AAFEATUREIMP drop constraint AAFEATUREIMP_FK01;
alter table DOTS.AAFEATUREIMP drop constraint AAFEATUREIMP_FK07;
alter table DOTS.AAGENE drop constraint AAGENE_FK04;
alter table DOTS.AAMOTIFGOTERMRULESET drop constraint
      AAMOTIFGOTERMRULESET_FK01;
alter table DOTS.AAMOTIFGOTERMRULESET drop constraint AAMOTIFGOTERMRULESET_FK02;
alter table DOTS.AASEQUENCEDBREF drop constraint AASEQUENCEDBREF_FK05;
alter table DOTS.AASEQUENCEKEYWORD drop constraint AASEQUENCEKEYWORD_FK05;
alter table DOTS.AASEQUENCEORGANELLE drop constraint AASEQUENCEORGANELLE_FK05;
alter table DOTS.AASEQUENCEREF drop constraint AASEQUENCEREF_FK02;
alter table DOTS.AASEQUENCESEQUENCEGROUP drop constraint 
      AASEQUENCESEQUENCEGROUP_FK01;
alter table DOTS.AASEQUENCETAXON drop constraint AASEQUENCETAXON_FK05;
alter table DOTS.NRDBENTRY drop constraint NRDBENTRY_FK01;
alter table DOTS.PROTEINPROPERTY drop constraint PROTEINPROPERTY_FK01;

drop table dots.aasequenceimp_old;

alter table dots.aasequenceimp add constraint PK_AASEQUENCEIMP 
      primary key (AA_SEQUENCE_ID);

alter table DOTS.AACOMMENT add constraint AACOMMENT_FK04 
      foreign key (AA_SEQUENCE_ID) references 
      DOTS.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DOTS.AAENTRY add constraint AAENTRY_FK04 
      foreign key (AA_SEQUENCE_ID) references 
      DOTS.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DOTS.AAFEATUREIMP add constraint AAFEATUREIMP_FK01 
      foreign key (AA_SEQUENCE_ID) references DOTS.AASEQUENCEIMP 
      (AA_SEQUENCE_ID);
alter table DOTS.AAFEATUREIMP add constraint AAFEATUREIMP_FK07 
      foreign key (MOTIF_AA_SEQUENCE_ID) references 
      DOTS.AASEQUENCEIMP (AA_SEQUENCE_ID);

alter table DOTS.AAGENE add constraint AAGENE_FK04 
      foreign key (AA_SEQUENCE_ID) references 
      DOTS.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DOTS.AAMOTIFGOTERMRULESET add constraint 
      AAMOTIFGOTERMRULESET_FK01 foreign key 
      (AA_SEQUENCE_ID_1) references DOTS.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DOTS.AAMOTIFGOTERMRULESET add constraint 
      AAMOTIFGOTERMRULESET_FK02 foreign key (AA_SEQUENCE_ID_2) 
      references DOTS.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DOTS.AASEQUENCEDBREF add constraint
      AASEQUENCEDBREF_FK05 foreign key (AA_SEQUENCE_ID) 
      references DOTS.AASEQUENCEIMP (AA_SEQUENCE_ID);

alter table DOTS.AASEQUENCEIMP add constraint AASEQUENCEIMP_FK05 
      foreign key (SOURCE_AA_SEQUENCE_ID) references 
      DOTS.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DOTS.AASEQUENCEKEYWORD add constraint AASEQUENCEKEYWORD_FK05 
      foreign key (AA_SEQUENCE_ID) references DOTS.AASEQUENCEIMP 
      (AA_SEQUENCE_ID);
alter table DOTS.AASEQUENCEORGANELLE add constraint 
      AASEQUENCEORGANELLE_FK05 foreign key (AA_SEQUENCE_ID)
       references DOTS.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DOTS.AASEQUENCEREF add constraint AASEQUENCEREF_FK02 
      foreign key (AA_SEQUENCE_ID) references DOTS.AASEQUENCEIMP 
      (AA_SEQUENCE_ID);
alter table DOTS.AASEQUENCESEQUENCEGROUP add constraint 
      AASEQUENCESEQUENCEGROUP_FK01 foreign key (AA_SEQUENCE_ID)	
      references DOTS.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DOTS.AASEQUENCETAXON add constraint AASEQUENCETAXON_FK05 
      foreign key (AA_SEQUENCE_ID) references DOTS.AASEQUENCEIMP 
      (AA_SEQUENCE_ID);
alter table DOTS.NRDBENTRY add constraint NRDBENTRY_FK01 foreign key 
      (AA_SEQUENCE_ID) references DOTS.AASEQUENCEIMP (AA_SEQUENCE_ID);
alter table DOTS.PROTEINPROPERTY add constraint PROTEINPROPERTY_FK01 
      foreign key (AA_SEQUENCE_ID) references DOTS.AASEQUENCEIMP 
      (AA_SEQUENCE_ID);

alter table dots.aasequenceimp add constraint AASEQUENCEIMP_FK04 foreign key 
      (EXTERNAL_DATABASE_RELEASE_ID) references SRES.EXTERNALDATABASERELEASE
       (EXTERNAL_DATABASE_RELEASE_ID);
alter table dots.aasequenceimp add constraint AASEQUENCEIMP_FK06 foreign key
      (SEQUENCE_TYPE_ID) references DOTS.SEQUENCETYPE (SEQUENCE_TYPE_ID)
alter table dots.aasequenceimp add constraint AASEQUENCEIMP_FK07 foreign key
      (SEQUENCE_ONTOLOGY_ID) references SRES.SEQUENCEONTOLOGY
       (SEQUENCE_ONTOLOGY_ID);
alter table dots.aasequenceimp add constraint AASEQUENCEIMP_FK08 foreign key
      (TAXON_ID) references SRES.TAXON (TAXON_ID);

create index DOTS.AASEQUENCEIMP_IND03 on dots.aasequenceimp 
       (SOURCE_AA_SEQUENCE_ID);
create index DOTS.AASEQUENCEIMP_IND04 on dots.aasequenceimp 
       (SUBCLASS_VIEW,STRING1,EXTERNAL_DATABASE_RELEASE_ID);
create index DOTS.AASEQUENCEIMP_IND05 on dots.aasequenceimp
        (SUBCLASS_VIEW,SOURCE_ID,EXTERNAL_DATABASE_RELEASE_ID);
create index DOTS.AASEQUENCEIMP_IND06 on dots.aasequenceimp
        (SUBCLASS_VIEW,AA_SEQUENCE_ID,SEQUENCE_VERSION);
create index DOTS.AASEQUENCEIMP_IND02 on dots.aasequenceimp
        (EXTERNAL_DATABASE_RELEASE_ID);
create index DOTS.AASEQUENCEIMP_IND08 on dots.aasequenceimp
        (SUBCLASS_VIEW,SOURCE_ID,STRING2);

CREATE TABLE DoTSVer.AASEQUENCEIMPVer (
    AA_SEQUENCE_ID		NUMBER(10)	NOT NULL,
    SEQUENCE_VERSION		NUMBER(3)	 NULL,
    SUBCLASS_VIEW	VARCHAR2(30)	NOT NULL,
    MOLECULAR_WEIGHT	NUMBER(12)	NULL,
    SEQUENCE	CLOB	NULL,
    LENGTH	NUMBER(12)	NULL,
    DESCRIPTION	VARCHAR2(1024)	NULL,
    EXTERNAL_DATABASE_RELEASE_ID	NUMBER(10)	NULL,
    SOURCE_ID	VARCHAR2(32)	NULL,
    SOURCE_AA_SEQUENCE_ID	NUMBER(10)	NULL,
    SEQUENCE_TYPE_ID		NUMBER(4)		NULL,
    SEQUENCE_ONTOLOGY_ID	  NUMBER(10)	NULL,
    TAXON_ID			  NUMBER(10)	NULL,
    TINYINT1	NUMBER(3)	NULL,
    STRING1	VARCHAR2(255)	NULL,
    STRING2	VARCHAR2(255)	NULL,
    STRING3	VARCHAR2(255)	NULL,
    STRING4	VARCHAR2(255)	NULL,
    INT1	NUMBER(12)	NULL,
    INT2	NUMBER(12)	NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(3)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(3)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL,
    VERSION_ALG_INVOCATION_ID	NUMBER(12)	NULL,
    VERSION_DATE		DATE		NULL,
    VERSION_TRANSACTION_ID	NUMBER(12)	NULL);

INSERT INTO DOTSVER.AASEQUENCEIMPVER SELECT
       AA_SEQUENCE_ID, SEQUENCE_VERSION, SUBCLASS_VIEW,
       MOLECULAR_WEIGHT, SEQUENCE, LENGTH, DESCRIPTION,
       EXTERNAL_DATABASE_RELEASE_ID, SOURCE_ID, 
       SOURCE_AA_SEQUENCE_ID, null, null, null, TINYINT1,
       STRING1, STRING2, STRING3, STRING4, INT1, INT2,
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID,
       VERSION_ALG_INVOCATION_ID, VERSION_DATE,
       VERSION_TRANSACTION_ID
       FROM DOTSVER.AASEQUENCEIMPVER_OLD;

DROP TABLE DOTSVER.AASEQUENCEIMPVER_OLD;

alter table dotsver.aasequenceimpver add constraint
      PK_AASEQUENCE primary key (AA_SEQUENCE_ID, MODIFICATION_DATE);

-- DoTS.NASequenceImp

CREATE TABLE DoTS.NASEQUENCEIMP (
    NA_SEQUENCE_ID	NUMBER(10)	NOT NULL,
    SEQUENCE_VERSION	NUMBER(3)	NOT NULL,
    SUBCLASS_VIEW	VARCHAR2(30)	NOT NULL,
    SEQUENCE_TYPE_ID	NUMBER(4)	NOT NULL,
    SEQUENCE_ONTOLOGY_ID		NUMBER(10)	NULL,
    TAXON_ID	NUMBER(12)	NULL,
    SEQUENCE	CLOB	NULL,
    LENGTH	NUMBER(12)	NULL,
    A_COUNT	NUMBER(12)	NULL,
    C_COUNT	NUMBER(12)	NULL,
    G_COUNT	NUMBER(12)	NULL,
    T_COUNT	NUMBER(12)	NULL,
    OTHER_COUNT	NUMBER(12)	NULL,
    DESCRIPTION	VARCHAR2(2000)	NULL,
    EXTERNAL_DATABASE_RELEASE_ID	NUMBER(5)	NULL,
    SOURCE_NA_SEQUENCE_ID	NUMBER(10)	NULL,
    SEQUENCE_PIECE_ID	NUMBER(10)	NULL,
    SEQUENCING_CENTER_CONTACT_ID	NUMBER(10)	NULL,
    STRING1	VARCHAR2(255)	NULL,
    STRING2	VARCHAR2(255)	NULL,
    STRING3	VARCHAR2(255)	NULL,
    STRING4	VARCHAR2(255)	NULL,
    STRING5	VARCHAR2(255)	NULL,
    TINYINT1	NUMBER(3)	NULL,
    INT1	NUMBER(12)	NULL,
    INT2	NUMBER(12)	NULL,
    INT3	NUMBER(12)	NULL,
    INT4	NUMBER(12)	NULL,
    INT5	NUMBER(12)	NULL,
    BIT1	NUMBER(1)	NULL,
    CLOB1	CLOB	NULL,
    CLOB2	CLOB	NULL,
    CLOB3	CLOB	NULL,
    CLOB4	CLOB	NULL,
    DATE1	DATE	NULL,
    DATE2	DATE	NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(3)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(3)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL);

INSERT INTO DoTS.NASEQUENCEIMP SELECT
       NA_SEQUENCE_ID, SEQUENCE_VERSION, SUBCLASS_VIEW,
       SEQUENCE_TYPE_ID, null, TAXON_ID, SEQUENCE, LENGTH,
       A_COUNT, C_COUNT, G_COUNT, T_COUNT, OTHER_COUNT,
       DESCRIPTION, EXTERNAL_DATABASE_RELEASE_ID, 
       SOURCE_NA_SEQUENCE_ID, SEQUENCE_PIECE_ID,
       SEQUENCING_CENTER_CONTACT_ID, STRING1, STRING2,
       STRING3, STRING4, STRING5, TINYINT1, INT1, INT2,
       INT3, INT4, INT5, BIT1, CLOB1, CLOB2, CLOB3, CLOB4,
       DATE1, DATE2,
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID
       FROM DOTS.NASEQUENCEIMP_OLD;

alter table DOTS.ASSEMBLYANATOMYPERCENT drop constraint 
      ASSEMBLYANATOMYPERCENT_FK01;
alter table DOTS.ASSEMBLYSEQUENCE drop constraint ASSEMBLYSEQUENCE_FK04;
alter table DOTS.ASSEMBLYSEQUENCE drop constraint ASSEMBLYSEQUENCE_FK05;
alter table DOTS.ASSEMBLYSNP drop constraint ASSEMBLYSNP_FK01;
alter table DOTS.BLATALIGNMENT drop constraint BLATALIGNMENT_FK01;
alter table DOTS.BLATALIGNMENT drop constraint BLATALIGNMENT_FK02;
alter table DOTS.CONSISTENTALIGNMENT drop constraint CONSISTENTALIGNMENT_FK05;
alter table DOTS.CONSISTENTALIGNMENT drop constraint CONSISTENTALIGNMENT_FK06;
alter table DOTS.DBREFNASEQUENCE drop constraint DBREFNASEQUENCE_FK05;
alter table DOTS.ENDSEQUENCEPAIRMAP drop constraint ENDSEQUENCEPAIRMAP_FK03;
alter table DOTS.ENDSEQUENCEPAIRMAP drop constraint ENDSEQUENCEPAIRMAP_FK04;
alter table DOTS.EPCR drop constraint EPCR_FK02;
alter table DOTS.EST drop constraint EST_FK06;
alter table DOTS.EXONLOCATION drop constraint EXONLOCATION_FK04;
alter table DOTS.GENEFEATURESAGETAGLINK drop constraint 
      GENEFEATURESAGETAGLINK_FK01;
alter table DOTS.GENEFEATURESEQOVERLAP drop constraint 
      GENEFEATURESEQOVERLAP_FK02;
alter table DOTS.GENEFEATURESEQOVERLAP drop constraint
      GENEFEATURESEQOVERLAP_FK03;
alter table DOTS.GENETRAPASSEMBLY drop constraint GENETRAPASSEMBLY_FK01;
alter table DOTS.GENETRAPASSEMBLY drop constraint GENETRAPASSEMBLY_FK02;
alter table DOTS.NACOMMENT drop constraint NACOMMENT_FK01;
alter table DOTS.NAENTRY drop constraint NAENTRY_FK04;
alter table DOTS.NAFEATUREIMP drop constraint NAFEATUREIMP_FK06;
alter table DOTS.NASEQCYTOLOCATION drop constraint NASEQCYTOLOCATION;
alter table DOTS.NASEQUENCEKEYWORD drop constraint NASEQUENCEKEYWORD_FK05;
alter table DOTS.NASEQUENCEORGANELLE drop constraint NASEQUENCEORGANELLE_FK05;
alter table DOTS.NASEQUENCEREF drop constraint NASEQUENCEREF_FK05;
alter table DOTS.OPTICALMAPALIGNMENT drop constraint OPTICALMAPALIGNMENT_FK02;
alter table DOTS.REPEATTYPE drop constraint REPEATTYPE_FK06;
alter table DOTS.SEQUENCEPIECE drop constraint SEQUENCEPIECE_FK04;
alter table DOTS.SEQUENCEPIECE drop constraint SEQUENCEPIECE_FK06;

drop table dots.nasequenceimp_old;

alter table dots.nasequenceimp add constraint 
      PK_NASEQUENCEIMP primary key (NA_SEQUENCE_ID);
alter table DOTS.ASSEMBLYANATOMYPERCENT add constraint 
      ASSEMBLYANATOMYPERCENT_FK01 foreign key (NA_SEQUENCE_ID) 
      references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DOTS.ASSEMBLYSEQUENCE add constraint ASSEMBLYSEQUENCE_FK04 
      foreign key (NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP 
      (NA_SEQUENCE_ID);
alter table DOTS.ASSEMBLYSEQUENCE add constraint ASSEMBLYSEQUENCE_FK05 
      foreign key (ASSEMBLY_NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP
       (NA_SEQUENCE_ID);
alter table DOTS.ASSEMBLYSNP add constraint ASSEMBLYSNP_FK01 foreign key 
      (NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DOTS.BLATALIGNMENT add constraint BLATALIGNMENT_FK01 foreign key
       (QUERY_NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DOTS.BLATALIGNMENT add constraint BLATALIGNMENT_FK02 foreign key
       (TARGET_NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);

alter table DOTS.CONSISTENTALIGNMENT add constraint CONSISTENTALIGNMENT_FK05 
      foreign key (GENOMIC_NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP 
      (NA_SEQUENCE_ID);
alter table DOTS.CONSISTENTALIGNMENT add constraint CONSISTENTALIGNMENT_FK06 
      foreign key (TRANSCRIPT_NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP 
      (NA_SEQUENCE_ID);
alter table DOTS.DBREFNASEQUENCE add constraint DBREFNASEQUENCE_FK05 
      foreign key (NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP 
      (NA_SEQUENCE_ID);
alter table DOTS.ENDSEQUENCEPAIRMAP add constraint ENDSEQUENCEPAIRMAP_FK03 
      foreign key (NA_SEQUENCE_ID_1) references DOTS.NASEQUENCEIMP 
      (NA_SEQUENCE_ID);
alter table DOTS.ENDSEQUENCEPAIRMAP add constraint ENDSEQUENCEPAIRMAP_FK04 
      foreign key (NA_SEQUENCE_ID_2) references DOTS.NASEQUENCEIMP 
      (NA_SEQUENCE_ID);
alter table DOTS.EPCR add constraint EPCR_FK02 foreign key (NA_SEQUENCE_ID)
       references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DOTS.EST add constraint EST_FK06 foreign key (NA_SEQUENCE_ID) 
      references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);

alter table DOTS.EXONLOCATION add constraint EXONLOCATION_FK04 foreign key 
      (NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DOTS.GENEFEATURESAGETAGLINK add constraint 
      GENEFEATURESAGETAGLINK_FK01 foreign key (GENOMIC_NA_SEQUENCE_ID) 
      references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DOTS.GENEFEATURESEQOVERLAP add constraint 
      GENEFEATURESEQOVERLAP_FK02 foreign key (GENOMIC_NA_SEQUENCE_ID) 
      references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DOTS.GENEFEATURESEQOVERLAP add constraint 
      GENEFEATURESEQOVERLAP_FK03 foreign key (SEQ_NA_SEQUENCE_ID) 
      references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DOTS.GENETRAPASSEMBLY add constraint GENETRAPASSEMBLY_FK01 
      foreign key (TAG_NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP 
      (NA_SEQUENCE_ID);
alter table DOTS.GENETRAPASSEMBLY add constraint GENETRAPASSEMBLY_FK02
       foreign key (ASSEMBLY_NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP
       (NA_SEQUENCE_ID);
alter table DOTS.NACOMMENT add constraint NACOMMENT_FK01 foreign key 
      (NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DOTS.NAENTRY add constraint NAENTRY_FK04 foreign key 
      (NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DOTS.NAFEATUREIMP add constraint NAFEATUREIMP_FK06 foreign key 
      (NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);

alter table DOTS.NASEQCYTOLOCATION add constraint NASEQCYTOLOCATION 
      foreign key (NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP 
      (NA_SEQUENCE_ID);
alter table DOTS.NASEQUENCEKEYWORD add constraint NASEQUENCEKEYWORD_FK05
      foreign key (NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP 
      (NA_SEQUENCE_ID);
alter table DOTS.NASEQUENCEORGANELLE add constraint NASEQUENCEORGANELLE_FK05 
      foreign key (NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP 
      (NA_SEQUENCE_ID);
alter table DOTS.NASEQUENCEREF add constraint NASEQUENCEREF_FK05 
      foreign key (NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP 
      (NA_SEQUENCE_ID);
alter table DOTS.OPTICALMAPALIGNMENT add constraint OPTICALMAPALIGNMENT_FK02 
      foreign key (NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP
      (NA_SEQUENCE_ID);
alter table DOTS.REPEATTYPE add constraint REPEATTYPE_FK06 foreign key
      (EXEMPLAR_NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table DOTS.SEQUENCEPIECE add constraint SEQUENCEPIECE_FK04 foreign key 
      (PIECE_NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);

alter table DOTS.SEQUENCEPIECE add constraint SEQUENCEPIECE_FK06 foreign key
      (VIRTUAL_NA_SEQUENCE_ID) references DOTS.NASEQUENCEIMP (NA_SEQUENCE_ID);
alter table dots.nasequenceimp add constraint NASEQUENCEIMP_FK05 
      foreign key (SEQUENCE_PIECE_ID) references DOTS.SEQUENCEPIECE 
      (SEQUENCE_PIECE_ID);

alter table dots.nasequenceimp add constraint NASEQUENCEIMP_FK06 
      foreign key (SEQUENCING_CENTER_CONTACT_ID) references 
      SRES.CONTACT (CONTACT_ID);
alter table dots.nasequenceimp add constraint NASEQUENCEIMP_FK01 
      foreign key (SEQUENCE_TYPE_ID) references DOTS.SEQUENCETYPE
       (SEQUENCE_TYPE_ID);
alter table dots.nasequenceimp add constraint NASEQUENCEIMP_FK02 
      foreign key (TAXON_ID) references SRES.TAXON (TAXON_ID);
alter table dots.nasequenceimp add constraint NASEQUENCEIMP_FK03 
      foreign key (EXTERNAL_DATABASE_RELEASE_ID) references 
      SRES.EXTERNALDATABASERELEASE (EXTERNAL_DATABASE_RELEASE_ID);
alter table dots.nasequenceimp add constraint NA_SEQ_ONTO_FK
      foreign key (SEQUENCE_ONTOLOGY_ID) references SRES.SEQUENCEONTOLOGY
      (SEQUENCE_ONTOLOGY_ID);

create index DOTS.NASEQUENCEIMP_IND01 on dots.nasequenceimp 
       (SUBCLASS_VIEW,STRING1,EXTERNAL_DATABASE_RELEASE_ID);
create index DOTS.NASEQUENCEIMP_IND15 on dots.nasequenceimp 
       (EXTERNAL_DATABASE_RELEASE_ID,TAXON_ID);
create index DOTS.NASEQUENCEIMP_IND02 on dots.nasequenceimp 
       (SEQUENCE_TYPE_ID);
create index DOTS.NASEQUENCEIMP_IND07 on dots.nasequenceimp (INT1);
create index DOTS.NASEQUENCEIMP_IND03 on dots.nasequenceimp 
       (SUBCLASS_VIEW,TAXON_ID);
create index DOTS.NASEQUENCEIMP_IND04 on dots.nasequenceimp 
       (EXTERNAL_DATABASE_RELEASE_ID);
create index DOTS.NASEQUENCEIMP_IND16 on dots.nasequenceimp (TAXON_ID);
create index DOTS.NASEQUENCEIMP_IND09 on dots.nasequenceimp 
       (STRING4,SUBCLASS_VIEW);
create index DOTS.NASEQUENCEIMP_IND10 on dots.nasequenceimp 
       (INT1,SUBCLASS_VIEW);
create index DOTS.NASEQUENCEIMP_IND13 on dots.nasequenceimp (STRING2);
create index DOTS.NASEQUENCEIMP_IND08 on dots.nasequenceimp 
       (EXTERNAL_DATABASE_RELEASE_ID,SUBCLASS_VIEW);
create index DOTS.NASEQUENCEIMP_IND17 on dots.nasequenceimp
        (SEQUENCING_CENTER_CONTACT_ID);
create index DOTS.NASEQUENCEIMP_IND05 on dots.nasequenceimp 
       (SEQUENCE_PIECE_ID);

CREATE TABLE DoTSVer.NASEQUENCEIMPVer (
    NA_SEQUENCE_ID	NUMBER(10)	NOT NULL,
    SEQUENCE_VERSION	NUMBER(3)	NOT NULL,
    SUBCLASS_VIEW	VARCHAR2(30)	NOT NULL,
    SEQUENCE_TYPE_ID	NUMBER(4)	NOT NULL,
    SEQUENCE_ONTOLOGY_ID		NUMBER(10)	NULL,
    TAXON_ID	NUMBER(12)	NULL,
    SEQUENCE	CLOB	NULL,
    LENGTH	NUMBER(12)	NULL,
    A_COUNT	NUMBER(12)	NULL,
    C_COUNT	NUMBER(12)	NULL,
    G_COUNT	NUMBER(12)	NULL,
    T_COUNT	NUMBER(12)	NULL,
    OTHER_COUNT	NUMBER(12)	NULL,
    DESCRIPTION	VARCHAR2(2000)	NULL,
    EXTERNAL_DATABASE_RELEASE_ID	NUMBER(5)	NULL,
    SOURCE_NA_SEQUENCE_ID	NUMBER(10)	NULL,
    SEQUENCE_PIECE_ID	NUMBER(10)	NULL,
    SEQUENCING_CENTER_CONTACT_ID	NUMBER(10)	NULL,
    STRING1	VARCHAR2(255)	NULL,
    STRING2	VARCHAR2(255)	NULL,
    STRING3	VARCHAR2(255)	NULL,
    STRING4	VARCHAR2(255)	NULL,
    STRING5	VARCHAR2(255)	NULL,
    TINYINT1	NUMBER(3)	NULL,
    INT1	NUMBER(12)	NULL,
    INT2	NUMBER(12)	NULL,
    INT3	NUMBER(12)	NULL,
    INT4	NUMBER(12)	NULL,
    INT5	NUMBER(12)	NULL,
    BIT1	NUMBER(1)	NULL,
    CLOB1	CLOB	NULL,
    CLOB2	CLOB	NULL,
    CLOB3	CLOB	NULL,
    CLOB4	CLOB	NULL,
    DATE1	DATE	NULL,
    DATE2	DATE	NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(3)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(3)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL,
    VERSION_ALG_INVOCATION_ID	NUMBER(12)	NULL,
    VERSION_DATE		DATE		NULL,
    VERSION_TRANSACTION_ID	NUMBER(12)	NULL);

INSERT INTO DoTSVer.NASEQUENCEIMPVEr SELECT
       NA_SEQUENCE_ID, SEQUENCE_VERSION, SUBCLASS_VIEW,
       SEQUENCE_TYPE_ID, null, TAXON_ID, SEQUENCE, LENGTH,
       A_COUNT, C_COUNT, G_COUNT, T_COUNT, OTHER_COUNT,
       DESCRIPTION, EXTERNAL_DATABASE_RELEASE_ID, 
       SOURCE_NA_SEQUENCE_ID, SEQUENCE_PIECE_ID,
       SEQUENCING_CENTER_CONTACT_ID, STRING1, STRING2,
       STRING3, STRING4, STRING5, TINYINT1, INT1, INT2,
       INT3, INT4, INT5, BIT1, CLOB1, CLOB2, CLOB3, CLOB4,
       DATE1, DATE2,
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID
       VERSION_ALG_INVOCATION_ID, VERSION_DATE,
       VERSION_TRANSACTION_ID
       FROM DOTSVER.NASEQUENCEIMPVER_OLD;

DROP TABLE DOTSVER.NASEQUENCEIMPVER_OLD;

alter table dotsver.nasequenceimpver add constraint
      PK_NASEQUENCE primary key (NA_SEQUENCE_ID, MODIFICATION_DATE);

-- DoTS.Gene

CREATE TABLE DoTS.GENE (
    GENE_ID	NUMBER(10)	NOT NULL,
    NAME	VARCHAR2(255)	NULL,
    GENE_SYMBOL	VARCHAR2(50)	NULL,
    GENE_CATEGORY_ID	NUMBER(10)	NULL,
    REVIEW_STATUS_ID	NUMBER(10)	NOT NULL,
    DESCRIPTION	VARCHAR2(500)	NULL,
    REVIEWER_SUMMARY	VARCHAR2(4000)	NULL,
    SEQUENCE_ONTOLOGY_ID	NUMBER(10) NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(3)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(3)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL);

INSERT INTO DoTS.GENE SELECT
       GENE_ID, NAME, GENE_SYMBOL, GENE_CATEGORY_ID,
       REVIEW_STATUS_ID, DESCRIPTIOn, REVIEWER_SUMMARY,
       null,
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID
       FROM DOTS.GENE_OLD;       

alter table DOTS.ALLELE drop constraint ALLELE_FK02;
alter table DOTS.FAMILYGENE drop constraint FAMILYGENE_FK03;
alter table DOTS.GENECHROMOSOMALLOCATION drop constraint 
      GENECHROMOSOMALLOCATION_FK01;
alter table DOTS.GENEFAMILYRELATION drop constraint GENEFAMILYRELATION_FK02;
alter table DOTS.GENEINSTANCE drop constraint GENEINSTANCE_FK06;
alter table DOTS.GENESYNONYM drop constraint GENESYNONYM_FK03;
alter table DOTS.RNA_OLD drop constraint RNA_FK05;

drop table dots.gene_old;

alter table dots.gene add constraint PK_GENE primary key (GENE_ID);

alter table DOTS.ALLELE add constraint ALLELE_FK02 
      foreign key (GENE_ID) references DOTS.GENE (GENE_ID);
alter table DOTS.FAMILYGENE add constraint FAMILYGENE_FK03 foreign key 
      (GENE_ID) references DOTS.GENE (GENE_ID);
alter table DOTS.GENECHROMOSOMALLOCATION add constraint 
      GENECHROMOSOMALLOCATION_FK01 foreign key (GENE_ID) 
      references DOTS.GENE (GENE_ID);
alter table DOTS.GENEFAMILYRELATION add constraint GENEFAMILYRELATION_FK02 
      foreign key (GENE_ID) references DOTS.GENE (GENE_ID);
alter table DOTS.GENEINSTANCE add constraint GENEINSTANCE_FK06 foreign key 
      (GENE_ID) references DOTS.GENE (GENE_ID);
alter table DOTS.GENESYNONYM add constraint GENESYNONYM_FK03 foreign key 
      (GENE_ID) references DOTS.GENE (GENE_ID);
alter table dots.gene add constraint GENE_FK04 foreign key (GENE_CATEGORY_ID)
       references DOTS.GENECATEGORY (GENE_CATEGORY_ID);
alter table dots.gene add constraint GENE_FK05 foreign key (REVIEW_STATUS_ID)
       references SRES.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table dots.gene add constraint GENE_FK_06 foreign key 
      (SEQUENCE_ONTOLOGY_ID) references SRES.SEQUENCEONTOLOGY 
      (SEQUENCE_ONTOLOGY_ID);

create index DOTS.GENE_IND05 on dots.gene (GENE_SYMBOL);
create index DOTS.GENE_IND02 on dots.gene (NAME);
create index DOTS.GENE_IND03 on dots.gene (GENE_CATEGORY_ID);
create index DOTS.GENE_IND04 on dots.gene (REVIEW_STATUS_ID);

CREATE TABLE DoTSVer.GENEVer (
    GENE_ID	NUMBER(10)	NOT NULL,
    NAME	VARCHAR2(255)	NULL,
    GENE_SYMBOL	VARCHAR2(50)	NULL,
    GENE_CATEGORY_ID	NUMBER(10)	NULL,
    REVIEW_STATUS_ID	NUMBER(10)	NOT NULL,
    DESCRIPTION	VARCHAR2(500)	NULL,
    REVIEWER_SUMMARY	VARCHAR2(4000)	NULL,
    SEQUENCE_ONTOLOGY_ID	NUMBER(10) NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(3)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(3)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL,
    VERSION_ALG_INVOCATION_ID	NUMBER(12)	NULL,
    VERSION_DATE		DATE		NULL,
    VERSION_TRANSACTION_ID	NUMBER(12)	NULL);

INSERT INTO DoTSVer.GENEVer SELECT
       GENE_ID, NAME, GENE_SYMBOL, GENE_CATEGORY_ID,
       REVIEW_STATUS_ID, DESCRIPTIOn, REVIEWER_SUMMARY,
       null,
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID,
       VERSION_ALG_INVOCATION_ID, VERSION_DATE,
       VERSION_TRANSACTION_ID
       FROM DOTSVer.GENEVer_OLD;       

DROP TABLE DOTSVER.GENEVER_OLD;

alter table dotsver.genever add constraint PK_GENE primary key
      (GENE_ID, MODIFICATION_DATE);

-- DoTS.RNA

CREATE TABLE DoTS.RNA (
    RNA_ID	NUMBER(10)	NOT NULL,
    DESCRIPTION	VARCHAR2(500)	NULL,
    REVIEW_STATUS_ID	NUMBER(1)	NOT NULL,
    GENE_ID	NUMBER(10)	NULL,
    REVIEWER_SUMMARY	VARCHAR2(4000)	NULL,
    SEQUENCE_ONTOLOGY_ID	NUMBER(10) NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(3)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(3)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL)

INSERT INTO DOTS.RNA SELECT
       RNA_ID, DESCRIPTION, REVIEW_STATUS_ID, GENE_ID,
       REVIEWER_SUMMARY, null,
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID
       FROM DOTS.RNA_OLD;       

alter table DOTS.PROTEIN_OLD drop constraint PROTEIN_FK01;
alter table DOTS.RNAANATOMY drop constraint RNAANATOMY_FK05;
alter table DOTS.RNAICONSTRUCT drop constraint RNAICONSTRUCT_FK01;
alter table DOTS.RNAINSTANCE drop constraint RNAINSTANCE_FK01;
alter table DOTS.RNARNACATEGORY drop constraint RNARNACATEGORY_FK06;

drop table dots.rna_old;

alter table dots.rna add constraint PK_RNA primary key (RNA_ID);
alter table DOTS.RNAANATOMY add constraint RNAANATOMY_FK05 foreign key 
      (RNA_ID) references DOTS.RNA (RNA_ID);
alter table DOTS.RNAICONSTRUCT add constraint RNAICONSTRUCT_FK01 foreign key 
      (RNA_ID) references DOTS.RNA (RNA_ID);
alter table DOTS.RNAINSTANCE add constraint RNAINSTANCE_FK01 foreign key 
      (RNA_ID) references DOTS.RNA (RNA_ID);
alter table DOTS.RNARNACATEGORY add constraint RNARNACATEGORY_FK06 foreign key 
      (RNA_ID) references DOTS.RNA (RNA_ID);
alter table dots.rna add constraint RNA_FK04 foreign key (REVIEW_STATUS_ID) 
      references SRES.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table dots.rna add constraint RNA_FK05 foreign key (GENE_ID) references
       DOTS.GENE (GENE_ID);
alter table dots.rna add constraint RNA_FK_06 foreign key 
      (SEQUENCE_ONTOLOGY_ID) references SRES.SEQUENCEONTOLOGY 
      (SEQUENCE_ONTOLOGY_ID);


create index DOTS.RNA_IND01 on dots.rna (REVIEW_STATUS_ID);
create index DOTS.RNA_IND02 on dots.rna (GENE_ID);

CREATE TABLE DoTSVer.RNAVer (
    RNA_ID	NUMBER(10)	NOT NULL,
    DESCRIPTION	VARCHAR2(500)	NULL,
    REVIEW_STATUS_ID	NUMBER(1)	NOT NULL,
    GENE_ID	NUMBER(10)	NULL,
    REVIEWER_SUMMARY	VARCHAR2(4000)	NULL,
    SEQUENCE_ONTOLOGY_ID	NUMBER(10) NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(3)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(3)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL,
    VERSION_ALG_INVOCATION_ID	NUMBER(12)	NULL,
    VERSION_DATE		DATE		NULL,
    VERSION_TRANSACTION_ID	NUMBER(12)	NULL);

 INSERT INTO DOTSVER.RNAVER SELECT
       RNA_ID, DESCRIPTION, REVIEW_STATUS_ID, GENE_ID,
       REVIEWER_SUMMARY, null,
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID,
       VERSION_ALG_INVOCATION_ID, VERSION_DATE,
       VERSION_TRANSACTION_ID
       FROM DOTSVER.RNAVER_OLD;       

drop table dotsver.rnaver_old;

alter table dotsver.rnaver add constraint PK_RNA primary key
      (RNA_ID, MODIFICATION_DATE);

-- DoTS.Protein

CREATE TABLE DoTS.PROTEIN (
    PROTEIN_ID	NUMBER(18)	NOT NULL,
    NAME	VARCHAR2(255)	NULL,
    RNA_ID	NUMBER(10)	NOT NULL,
    REVIEW_STATUS_ID	NUMBER(10)	NOT NULL,
    DESCRIPTION	VARCHAR2(500)	NULL,
    REVIEWER_SUMMARY	VARCHAR2(4000)	NULL,
    SEQUENCE_ONTOLOGY_ID	NUMBER(10) NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(3)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(3)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL);

Insert INTO DoTS.PROTEIN SELECT
       PROTEIN_ID, NAME, RNA_ID, 
       REVIEW_STATUS_ID, DESCRIPTION, REVIEWER_SUMMARY,
       null,
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID
       FROM DOTS.PROTEIN_OLD;

alter table DOTS.FAMILYPROTEIN drop constraint FAMILYPROTEIN_FK05;
alter table DOTS.PROTEININSTANCE drop constraint PROTEININSTANCE_FK02;
alter table DOTS.PROTEINPROTEINCATEGORY drop constraint 
      PROTEINPROTEINCATEGORY_FK01;
alter table DOTS.PROTEINSYNONYM drop constraint PROTEINSYNONYM_FK04;

drop table dots.protein_old;

alter table dots.protein add constraint PK_PROTEIN primary key (PROTEIN_ID);
alter table DOTS.FAMILYPROTEIN add constraint FAMILYPROTEIN_FK05 foreign key 
      (PROTEIN_ID) references DOTS.PROTEIN (PROTEIN_ID);
alter table DOTS.PROTEININSTANCE add constraint PROTEININSTANCE_FK02 
      foreign key (PROTEIN_ID) references DOTS.PROTEIN (PROTEIN_ID);
alter table DOTS.PROTEINPROTEINCATEGORY add constraint 
      PROTEINPROTEINCATEGORY_FK01 foreign key (PROTEIN_ID) 
      references DOTS.PROTEIN (PROTEIN_ID);
alter table DOTS.PROTEINSYNONYM add constraint PROTEINSYNONYM_FK04 
      foreign key (PROTEIN_ID) references DOTS.PROTEIN (PROTEIN_ID);
alter table dots.protein add constraint PROTEIN_FK01 foreign key (RNA_ID)
      references DOTS.RNA (RNA_ID);
alter table dots.protein add constraint PROTEIN_FK06 foreign key 
      (REVIEW_STATUS_ID) references SRES.REVIEWSTATUS (REVIEW_STATUS_ID);
alter table dots.protein add constraint PROTEIN_FK_07 foreign key 
      (SEQUENCE_ONTOLOGY_ID) references SRES.SEQUENCEONTOLOGY 
      (SEQUENCE_ONTOLOGY_ID);

create index DOTS.PROTEIN_IND02 on dots.protein (PROTEIN_ID,RNA_ID);
create index DOTS.PROTEIN_IND01 on dots.protein (RNA_ID);
create index DOTS.PROTEIN_IND03 on dots.protein (REVIEW_STATUS_ID);

CREATE TABLE DoTSVer.PROTEINVer (
    PROTEIN_ID	NUMBER(18)	NOT NULL,
    NAME	VARCHAR2(255)	NULL,
    RNA_ID	NUMBER(10)	NOT NULL,
    REVIEW_STATUS_ID	NUMBER(10)	NOT NULL,
    DESCRIPTION	VARCHAR2(500)	NULL,
    REVIEWER_SUMMARY	VARCHAR2(4000)	NULL,
    SEQUENCE_ONTOLOGY_ID	NUMBER(10) NULL,
    MODIFICATION_DATE	DATE	NOT NULL,
    USER_READ	NUMBER(1)	NOT NULL,
    USER_WRITE	NUMBER(1)	NOT NULL,
    GROUP_READ	NUMBER(1)	NOT NULL,
    GROUP_WRITE	NUMBER(1)	NOT NULL,
    OTHER_READ	NUMBER(1)	NOT NULL,
    OTHER_WRITE	NUMBER(1)	NOT NULL,
    ROW_USER_ID	NUMBER(12)	NOT NULL,
    ROW_GROUP_ID	NUMBER(3)	NOT NULL,
    ROW_PROJECT_ID	NUMBER(3)	NOT NULL,
    ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL,
    VERSION_ALG_INVOCATION_ID	NUMBER(12)	NULL,
    VERSION_DATE		DATE		NULL,
    VERSION_TRANSACTION_ID	NUMBER(12)	NULL);

INSERT INTO DoTSVer.ProteinVer SELECT
       PROTEIN_ID, NAME, RNA_ID, 
       REVIEW_STATUS_ID, DESCRIPTION, REVIEWER_SUMMARY,
       null,
       MODIFICATION_DATE, USER_READ, USER_WRITE, GROUP_READ,
       GROUP_WRITE, OTHER_READ, OTHER_WRITE, ROW_USER_ID,
       ROW_GROUP_ID, ROW_PROJECT_ID, ROW_ALG_INVOCATION_ID,
       VERSION_ALG_INVOCATION_ID, VERSION_DATE,
       VERSION_TRANSACTION_ID
       FROM DotsVer.ProteinVer_OLD;       

drop table dotsver.proteinver_old;

alter table dotsver.proteinver add constraint PK_PROTEIN primary key
      (PROTEIN_ID, MODIFICATION_DATE);

--
-- NEW TABLES
--

-- A new table, Core.DatabaseVersion is being created which will
-- hold the GUS version for use with plugins.  The version column
-- is being removed from Core.DatabaseInfo (which is really schema 
-- info)

CREATE SEQUENCE CORE.DATABASEVERSION_SQ START WITH 1;

CREATE TABLE Core.DatabaseVersion (
       DATABASE_VERSION_ID	NUMBER(5)	NOT NULL,
       VERSION			FLOAT		NOT NULL,
       MODIFICATION_DATE	DATE		NOT NULL,
       USER_READ		NUMBER(1)       NOT NULL,
       USER_WRITE		NUMBER(1)	NOT NULL,
       GROUP_READ		NUMBER(1)	NOT NULL,
       GROUP_WRITE		NUMBER(1)	NOT NULL,
       OTHER_READ		NUMBER(1)	NOT NULL,
       OTHER_WRITE		NUMBER(1)	NOT NULL,
       ROW_USER_ID		NUMBER(12)	NOT NULL,
       ROW_GROUP_ID		NUMBER(12)	NOT NULL, 
       ROW_PROJECT_ID		NUMBER(12)	NOT NULL,
       ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL
);

CREATE TABLE CoreVer.DatabaseVersionVer (
       DATABASE_VERSION_ID	NUMBER(5)	NOT NULL,
       VERSION			FLOAT		NOT NULL,
       MODIFICATION_DATE	DATE		NOT NULL,
       USER_READ		NUMBER(1)       NOT NULL,
       USER_WRITE		NUMBER(1)	NOT NULL,
       GROUP_READ		NUMBER(1)	NOT NULL,
       GROUP_WRITE		NUMBER(1)	NOT NULL,
       OTHER_READ		NUMBER(1)	NOT NULL,
       OTHER_WRITE		NUMBER(1)	NOT NULL,
       ROW_USER_ID		NUMBER(12)	NOT NULL,
       ROW_GROUP_ID		NUMBER(12)	NOT NULL, 
       ROW_PROJECT_ID		NUMBER(12)	NOT NULL,
       ROW_ALG_INVOCATION_ID	NUMBER(12)	NOT NULL,
       VERSION_ALG_INVOCATION_ID NUMBER(12),
       VERSION_DATE		DATE,
       VERSION_TRANSACTION_ID	NUMBER(12)
);

ALTER TABLE Core.DatabaseVersion ADD CONSTRAINT DatabaseVersion_PK
      PRIMARY KEY (DATABASE_VERSION_ID);

ALTER TABLE CoreVer.DatabaseVersionVer ADD CONSTRAINT DatabaseVersion_PK
      PRIMARY KEY (DATABASE_VERSION_ID, MODIFICATION_DATE);

ALTER TABLE CORE.DATABASEINFO DROP COLUMN VERSION;

ALTER TABLE COREVER.DATABASEINFOVER DROP COLUMN VERSION;

--ALTER TABLE SRES.EXTERNALDATABASE DROP COLUMN LOWERCASE_NAME;
--ALTER TABLE SRESVER.EXTERNALDATABASEVER DROP COLUMN LOWERCASE_NAME;

-- A new table, Core.AnalysisAlgorithm is being created to provide any
-- information about a particular analysis to any row in the database.

--- REVIEW
-- As part of this change, algorithm_id will be removed from Dots.Similarity,
-- DoTS.SeqGroupExpirementImp (and views), and DoTS.OpticalMapAlignment. A
-- data migration script has been provided to move these rows.

create sequence core.analysisalgorithm_sq start with 1;

create table core.analysisalgorithm (
        analysis_algorithm_id   number(10) not null,
        table_id                number(5) not null,
        row_id                  number(12) not null,
        algorithm_invocation_id number(12) not null,
        modification_date       date not null,
        user_read               number(1) not null,
        user_write              number(1) not null,
        group_read              number(1) not null,
        group_write             number(1) not null,
        other_read              number(1) not null,
        other_write             number(1) not null,
        row_user_id             number(12) not null,
        row_group_id            number(3) not null,
        row_project_id          number(4) not null,
        row_alg_invocation_id   number(12) not null
);

create table corever.analysisalgorithmver (
        analysis_algorithm_id   number(10) not null,
        table_id                number(5) not null,
        row_id                  number(12) not null,
        algorithm_invocation_id number(12) not null,
        modification_date       date not null,
        user_read               number(1) not null,
        user_write              number(1) not null,
        group_read              number(1) not null,
        group_write             number(1) not null,
        other_read              number(1) not null,
        other_write             number(1) not null,
        row_user_id             number(12) not null,
        row_group_id            number(3) not null,
        row_project_id          number(4) not null,
        row_alg_invocation_id   number(12) not null,
       VERSION_ALG_INVOCATION_ID NUMBER(12),
       VERSION_DATE		DATE,
       VERSION_TRANSACTION_ID	NUMBER(12)
);

ALTER TABLE Core.AnalysisAlgorithm Add Constraint AnalysisAlgorithm_PK
      PRIMARY KEY (Analysis_Algorithm_ID);

ALTER TABLE CoreVer.AnalysisAlgorithmVer Add Constraint AnalysisAlgorithm_PK
      PRIMARY KEY (Analysis_Algorithm_ID, MODIFICATION_DATE);

Alter Table Core.AnalysisAlgorithm Add Constraint AnalysisAlgorithm_FK01
      FOREIGN KEY (TABLE_ID) REFERENCES Core.TableInfo (TABLE_ID);

Alter Table Core.AnalysisAlgorithm Add Constraint AnalysisAlgorithm_FK02
      FOREIGN KEY (Algorithm_Invocation_ID) REFERENCES Core.AlgorithmInvocation
      (ALGORITHM_INVOCATION_ID);

Alter Table DoTS.Similarity Drop Column ALGORITHM_ID;
Alter Table DotsVer.SimilarityVer Drop Column ALGORITHM_ID;

Alter Table DoTS.OpticalMapAlignment Drop Column ALGORITHM_ID;
Alter Table DotsVer.OpticalMapAlignmentVer Drop Column ALGORITHM_ID;

Alter Table DoTS.SeqGroupExperimentImp Drop Column ALGORITHM_ID;
Alter Table DoTSVer.SeqGroupExperimentImpVer Drop Column Algorithm_ID;

--
-- DEPRECATED TABLES
-- 

-- The core.machine table has been deprecated.  There is no replacement or 
-- data migration script provided.

alter table CORE.ALGORITHMINVOCATION drop constraint ALGORITHMINVOCATION_FK04;

alter table core.algorithminvocation drop column machine_id;
alter table corever.algorithminvocationver drop column machine_id;

DROP TABLE CORE.MACHINE;
DROP TABLE COREVER.MACHINEVER;

delete from core.databasedocumentation where table_id=
(select t.table_id from core.tableinfo t, core.databaseinfo d 
	where lower(t.name)='machine' and lower(d.name)='core');
delete from core.databasedocumentation where table_id=
(select t.table_id from core.tableinfo t, core.databaseinfo d 
	where lower(t.name)='machinever' and lower(d.name)='corever');

delete from core.tableinfo where lower(name)='machine' and database_id=(
       select database_id from core.databaseinfo where lower(name)='core');
delete from core.tableinfo where lower(name)='machinever' and database_id=(
       select database_id from core.databaseinfo where lower(name)='corever');

-- DoTS.GeneAlias has been merged with DoTS.GeneSynonym.  A data migration 
-- script is provided below. ** VERIFY that this is logical for your DB!

-- Make sure no rows soft link to GENE.ALIAS

delete from core.databasedocumentation where table_id=
(select t.table_id from core.tableinfo t, core.databaseinfo d 
	where lower(t.name)='genealias' and lower(d.name)='dots');
delete from core.databasedocumentation where table_id=
(select t.table_id from core.tableinfo t, core.databaseinfo d 
	where lower(t.name)='genealiasver' and lower(d.name)='dotsver');

delete from core.tableinfo where lower(name)='genealias' and database_id=(
       select database_id from core.databaseinfo where lower(name)='dots');
delete from core.tableinfo where lower(name)='genealiasver' and database_id=(
       select database_id from core.databaseinfo where lower(name)='dotsver');

-- Move rows from GeneAlias to GeneSynonym

INSERT INTO DOTS.GENESYNONYM SELECT
       DOTS.GENESYNONYM_SQ.nextval,
       GENE_ID,
       GENE_ALIAS_NAME,
       REVIEW_STATUS_ID,
       NULL,
       MODIFICATION_DATE,
       USER_READ,
       USER_WRITE,
       GROUP_READ,
       GROUP_WRITE,
       OTHER_READ,
       OTHER_WRITE,
       ROW_USER_ID,
       ROW_GROUP_ID,
       ROW_PROJECT_ID,
       ROW_ALG_INVOCATION_ID
    FROM DOTS.GENEALIAS;

INSERT INTO DOTSVER.GENESYNONYMVER SELECT
       GENE_ALIAS_ID,
       GENE_ID,
       GENE_ALIAS_NAME,
       REVIEW_STATUS_ID,
       NULL,
       MODIFICATION_DATE,
       USER_READ,
       USER_WRITE,
       GROUP_READ,
       GROUP_WRITE,
       OTHER_READ,
       OTHER_WRITE,
       ROW_USER_ID,
       ROW_GROUP_ID,
       ROW_PROJECT_ID,
       ROW_ALG_INVOCATION_ID,
       VERSION_ALG_INVOCATION_ID,
       VERSION_DATE,
       VERSION_TRANSACTION_ID
    FROM DOTSVER.GENEALIASVER;

DROP TABLE DOTS.GENEALIAS;
DROP TABLE DOTSVER.GENEALIASVER;

-- RAD3.Process tables have been deprecated. 
-- No data migration scripts are provided.

DROP TABLE RAD3.PROCESSIOELEMENT;
DROP TABLE RAD3.PROCESSIO;
DROP TABLE RAD3.PROCESSINVOCATIONPARAM;
DROP TABLE RAD3.PROCESSINVQUANTIFICATION;
DROP TABLE RAD3.PROCESSINVOCATION;
DROP TABLE RAD3.PROCESSIMPLEMENTATION;
DROP TABLE RAD3.PROCESSIMPLEMENTATIONPARAM;
DROP TABLE RAD3.PROCESSRESULT;

DROP TABLE RAD3VER.PROCESSIOELEMENTVER;
DROP TABLE RAD3VER.PROCESSIOVER;
DROP TABLE RAD3VER.PROCESSINVOCATIONPARAMVER;
DROP TABLE RAD3VER.PROCESSINVQUANTIFICATIONVER;
DROP TABLE RAD3VER.PROCESSINVOCATIONVER;
DROP TABLE RAD3VER.PROCESSIMPLEMENTATIONVER;
DROP TABLE RAD3VER.PROCESSIMPLEMENTATIONPARAMVER;
DROP TABLE RAD3VER.PROCESSRESULTVER;

-- The RAD3.GNFAffymetixResult view has been deprecated.

DROP VIEW RAD3.GNFAffymetrixResult;
-- Delete rows?

---
--- Schema rename
--- 

-- The RAD3 schema has been renamed to RAD.  The easiest way to do this change
-- is to use Oracle's imp/exp utility:

-- exp rad3@instance file=rad3.dmp log=rad3.log owner=rad3 full=y
-- exp rad3ver@instance file=rad3ver.dmp log=rad3ver.log owner=rad3ver

-- You must now create the RAD and RADVER users, and grant them appropriate
-- privileges.  Use the grantPermissions script to grant REFERENCES:

grantPermissions.pl --login=Core --owner=Core --permissions=REFERENCES --grantees=RAD --db-sid=gus35 --db-host=cbildb01.pcbi.upenn.edu --db-port=1521
grantPermissions.pl --login=SRes --owner=SRes --permissions=REFERENCES --grantees=RAD --db-sid=gus35 --db-host=cbildb01.pcbi.upenn.edu --db-port=1521
grantPermissions.pl --login=DoTS --owner=DoTS --permissions=REFERENCES --grantees=RAD --db-sid=gus35 --db-host=cbildb01.pcbi.upenn.edu --db-port=1521

-- imp rad@instance file=rad3.dmp log=rad3imp.log fromuser=rad3 touser=rad
-- imp rad@instance file=rad3.dmp log=rad3imp.log fromuser=rad3 touser=rad

update core.databaseinfo set name='RAD' where lower(name)='rad3';
update core.databaseinfo set name='RADVer' where lower(name)='rad3ver';
